### ISSUE TITLE
Re-generate (or drop) ICC pre-built assembler files

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1065]
Last commit for the .S files is May 8, 2014 while the C source has had several updates since.

**Comment by magnumripper** [comment]
I just tried a build `--with-icc-asm` on Super and it worked just fine. All self-tests pass. The changes since last icc commit are minor but some of them are probably needed - we should update these files or ditch them.

Like I just wrote to ML, SHA1 and SHA2 speeds are not faster, but slower (compared to gcc 4.4). SHA2 doesn't have interleaving. MD4 and MD5 are significantly faster using icc stuff.

**Comment by jfoug** [comment]
Just a NOTE:

sse files were touched once again.   Added new flag (for SHA formats)  SSEi_FLAT_RELOAD_SWAPLAST

This is used in the SybaseASE format. it does 9 limb sha512's, and the first 8 should have the last QWORD swapped.  That is what that flag is for.  So it 100% assured, that if older icc .S files were used, that format would fail now.

**Comment by jfoug** [comment]
Note2:

I am not sure these are needed any more. The  only time they 'helped' that I am aware of, was on some older 32 bit builds.  But must of the compilers have updated to the point that gcc is as fast (or faster) than we were seeing with ICC, or at least it is very close.  I can not speak for MinGW.  It may still be behind, BUT I think the underlying compiler for cygwin IS mingw, so it may be just fine also.

I really think would should look long and hard, and make some choice, just like with did with the very old mmx-coef.S files, and see that they served their purpose at one time, but over the years, all they are is extra complexity to the build process, and worse yet, outdated so that if someone actually DID use them, they would be a problem.

Now, if we do drop them, we certainly could keep the perl script to re-make them, BUT  I am not 100% sure this would work without the legacy build system, which we are also looking at putting into the dustbin of history.

It really might be high time to move on for some of these things.......

**Comment by magnumripper** [comment]
For MD4 and MD5, gcc is still *far* behind icc.

**Comment by magnumripper** [comment]
I added the bug label now, since the current files no longer will work. We need to update, or drop the support.

**Comment by jfoug** [comment]
> For interleaved MD4/MD5, gcc is still far behind icc.

But that may also be 'how' we have implemented the SIMD stuff.  I have not looked for years, but I bet there are better ways.  I really wish I still had VTUNE.   I bet we have stalls all over the place, due to how we have code laid out.  That is one 'good' thing that icc does, is it does the processing sort of like VTune, by actually running, watching how it interplays, and reordering where possible to avoid stalls.  But I am pretty sure that we 'could' do the same thing for GCC if we really put our minds to it.

> Solar wants us to keep it.

Yes, and he also wants to keep legacy, the OLD mmx asm crap, etc, etc.  Sometime the cobwebs simply NEED to be swept away.  Btw, solar was NOT happy originally about the icc generated .S files.  What changed??

**Comment by magnumripper** [comment]
> Btw, solar was NOT happy originally about the icc generated .S files.

LOL, that's true!

**Comment by magnumripper** [comment]
This will be dropped before releasing Jumbo-2 unless someone volunteers to re-build the files.

**Comment by magnumripper** [comment]
It now hit me we have icc on super. So I tried rebuilding.
```
$ make -f Makefile.legacy intrinsics
rm -f sse-intrinsics-64.S sse-intrinsics-32.S sse-intrinsics-win32.S
ln -f -s x86-64.h arch.h
icc -S -o sse-intrinsics-64.S sse-intrinsics.c -O2 -fno-builtin -fno-verbose-asm -openmp -DUSING_ICC_S_FILE  -Wall
ln -f -s x86-sse.h arch.h
icc -m32 -S -o sse-intrinsics-32.S sse-intrinsics.c -O2 -fno-builtin -fno-verbose-asm -openmp -DUSING_ICC_S_FILE  -Wall
perl sse2i_winfix.pl sse-intrinsics-32.S sse-intrinsics-win32.S
mv sse-intrinsics-win32.S sse-intrinsics-32.S
```
No problem with that.

But when trying to use it with `./configure --with-icc-asm` there's some problems.
```
sse-intrinsics-64.o: In function `md5cryptsse':
sse-intrinsics.c:(.text+0x7c1f): undefined reference to `john_MD5_Init'
sse-intrinsics.c:(.text+0x7c43): undefined reference to `john_MD5_Update'
sse-intrinsics.c:(.text+0x7c64): undefined reference to `john_MD5_Update'
sse-intrinsics.c:(.text+0x7c87): undefined reference to `john_MD5_Update'
sse-intrinsics.c:(.text+0x7ca4): undefined reference to `john_MD5_Update'
sse-intrinsics.c:(.text+0x7cb1): undefined reference to `john_MD5_Init'
sse-intrinsics.c:(.text+0x7cce): undefined reference to `john_MD5_Update'
sse-intrinsics.c:(.text+0x7ceb): undefined reference to `john_MD5_Update'
sse-intrinsics.c:(.text+0x7d08): undefined reference to `john_MD5_Update'
sse-intrinsics.c:(.text+0x7d1d): undefined reference to `john_MD5_Final'
sse-intrinsics.c:(.text+0x7d3a): undefined reference to `john_MD5_Update'
sse-intrinsics.c:(.text+0x7d77): undefined reference to `john_MD5_Update'
sse-intrinsics.c:(.text+0x7d8e): undefined reference to `john_MD5_Update'
sse-intrinsics.c:(.text+0x7db3): undefined reference to `john_MD5_Final'
collect2: ld returned 1 exit status
make[1]: *** [../run/john] Error 1
make: *** [default] Error 2
```
Probably some marshalling that changed again.

**Comment by magnumripper** [comment]
This time it was our own marshalling, lol.
