### ISSUE TITLE
memory allocationb error in django-scrypt format

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1070]
Running the TS with  an --enable-asan --enable-memdbg-ex build.
```

...form=cisco9                       guesses: 1500 0:00:00:02 DONE  [PASSED]
.pot CHK:cisco9                   guesses: 1500 0:00:00:01 DONE  [PASSED] (1500 val-pwd)
sh: line 1: 18668 Killed                  ../run/john -ses=./tst --fork=2 -pot=./tst.pot django-scrypt_tst.in --wordlist=pw-200.dic -form=django-scrypt 2>&1 > /dev/null

form=django-scrypt                guesses:    0 -show= 779 unk unk : Expected count(s) (1500)  [!!!FAILED2!!!  return code 35072]
Exiting on error. The .pot file ./tst.pot contains the found data
The command used to run this test was:

../run/john -ses=./tst  --fork=2 -pot=./tst.pot django-scrypt_tst.in --wordlist=pw-200.dic -form=django-scrypt
```

After consuming more and more memory
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                
19067 fd        20   0 16.888t 7.156g   1744 R  84.2 92.3   0:59.03 ../run/john -ses=./tst -pot=./tst.pot django-scrypt_tst.in --wordlist=pw-200.dic -form=django-scrypt           
```
john finally gets killed.

When I re-run this, and jjust restore the session aborted earlier, I finally get
```
Use the "--show" option to display all of the cracked passwords reliably
Main process session completed, but some child processes failed
At Program Exit
MemDbg_Validate level 0 checking Passed
MemDbg_Validate level 1 checking Passed
MemDbg_Validate level 2 checking Passed
MemDbg_Validate level 3 checking Passed
```
So, memdbg doesn't find anything unusual.

When running
```
OMP_NUM_THREADS=2 ../run/john -ses=./tst -pot=./tst.pot django-scrypt_tst.in --wordlist=pw-200.dic -form=django-scrypt
```
I get
```
ERROR: Failed to mmap
```

**Comment by jfoug** [comment]
Stop using -memdbg-ex

**Comment by frank-dittrich** [comment]
Then why does memdbg-ex exist, if it is of no use?

And why does this problem only occur for django-scrypt and rar?

**Comment by jfoug** [comment]
It is of use for exacting targeted debugging. It is probably MUCH less of use now that we have ASAN in the john code.  Asan does much more, and better.  

What memdbg-ex does is to 'never' release memory.  It simply flags a buffer as freed, but does not delete. It helps find memory being used after freed.  However, it has been neutered and broken, due to some format requirements, and NOW with mmap, I am not 100% sure I can get it working.  Before, if it tailed to pull memory, it would start to free up oldest memory until the allocation fails. But there is nothing I can do where other memory functions (such as mmap) want memory and fail.  

Alone the fact that memdbg in ex mode is having to free memory makes it somewhat non useful for doing wide testing, and really a problem on some formats which do a lot of internal allocations in the inner loop (rar, pdf, any scrypt, etc).  Those formats are simply not suited for a memory tool such as this, where the tool does not tied into the compiler to use special instrumentation.

I am keeping it in there, for a couple reasons.  1. I simply do not have time or desire to remove it, and validate that everything still functions properly.  2. if used for what it was intended for, it does have merit.

**Comment by magnumripper** [comment]
I too think we should keep it, for the occasional (and very specific) cases we need it. Just don't use it for anything else.

**Comment by jfoug** [comment]
This was the intention. it is for very specific problem solving.  It was never designed to flush out 'knonwn' problems.  The standard memdbg WAS designed to flush out unknown issues.  It can also track down known problems (such as when you run in this manner for a while, memory grows).  But the standard memdbg it works really well to simply sit in the background running, and it 'alarms' when there are problems, AND gives a canary signal at exit listing memory being all freed or not.
