### ISSUE TITLE
PCAP2john enhancements

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1097]
We could consider adding code from (and/or submitting code to) https://github.com/DanMcInerney/net-creds.git

**Comment by kholia** [comment]
Ettercap and BetterCAP are dedicated and well maintained tools which should be able to do most of the stuff done by `net-creds`. We shouldn't try to replicate the functionality provided by Ettercap / BetterCAP tools.

There is some terrible quality code in `net-creds`.

https://github.com/DanMcInerney/net-creds/blob/master/net-creds.py#L236
https://github.com/DanMcInerney/net-creds/blob/master/net-creds.py#L284

Instead of properly decoding ASN.1 messages, `net-creds` relies on unreliable hardcoded offsets!

Overall, there is not much left to do in this issue. Hence, I am closing this issue. Please re-open if there are some specific action items for us.
