### ISSUE TITLE
memdbg should never return memory aligned better than requested

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1195]
Maybe this is already implemented? If not, it's probably a good idea for catching bugs.

**Comment by magnumripper** [comment]
Blocked by #1200

**Comment by magnumripper** [comment]
This is no longer completely blocked by #1200. And anyway, we can implement this in mem_alloc_tiny() right away.

So how do we go about doing it? For mem_alloc_tiny() it should be easy:
* Original request is size, align.
* We do `size += align`.
* We alloc as usual.
* We check alignment. If it's better than requested, we bump the pointer with *align*.
* Done.

I need to think this over. Is it this simple? I think it is.

**Comment by magnumripper** [comment]
Done! Works like a champ.

**Comment by magnumripper** [comment]
Not sure if we can do this at all in memdbg, without completely changing how it does things. OTOH that will be needed for #1200 anyway.

**Comment by magnumripper** [comment]
Not a single salt/binary align bug found. We must have fixed the last one JUST before implementing this! Doh! But we'll find them easily in the future.

**Comment by jfoug** [comment]
I am planning on revamp of memdbg. I will do this with 2 headers. The first header will have a magic value, a pointer to the 2Nd header, and a fence post. The fence post will butt up to the start of the memory. There will be at least 4 bytes of fence post, possibly more. The pointer will be 16 byte aligned. And at least 4 bytes preceeding the memory buffer. Computing the location of this pointer can be done only knowing the iser memory ponter. Just before this pointer is anouther magic value that will validate the pointer as not being overwritten. There will likely be memory allocated in front of this header. That memory is unused. Trailing the user memory will be a fence post. Following the fence post, on an even 16 byte offset will be header 2. This header will be similar to the current first header, but it will also have a pointer to the actual allocated buffer, ie, somewhere in front of the first header. 

Simple stuff, but may take a bit of debugging to get everything working right. But with this new design, we can get the user memory to start at any offset, since the first header is no longer fixed size

**Comment by frank-dittrich** [comment]
On 05/22/2015 10:06 PM, magnum wrote:
> Not a single salt/binary align bug found. We must have fixed the last
> one JUST before implementing this! Doh! But we'll find them easily in
> the future.

Did you test on non-x86?

**Comment by magnumripper** [comment]
> Did you test on non-x86?

No, but few formats differ in binary/salt.

**Comment by jfoug** [comment]
This should be fixed (I think) in 20ce8fe 

There is a #define in john.c  (at the very start of main) that should test memdbg.  It simple tests all alignments from 1 to 256.  It checks that the alignment is correct. It also tests that the pointer/align is not %=0 to the alignment.  The only one that 'is' %=0 to alignment is alignment 1.

After this change, I see no salt() misalignments. They should show up now.

**Comment by magnumripper** [comment]
Cool. These things will make our annual Sparc sessions much shorter :)

**Comment by jfoug** [comment]
The biggest thing is where there is insufficient salt/binary alignment.  Say it is 1, but needs to be sizeof(int) or something.

On -test=0, xsha512 is now failing. Pomelo still fails, but there was never an attempt to get it working.

**Comment by jfoug** [comment]
I found a core in hmacSHA384.  It was allocations of the ipad/opad ctx vars. We were aligning to ARCH_WORD, but on 32 bit systems, that is only 4 bytes (8 bytes is the size of the 64 bit data).  This did not show up on -test=0, but was found with the TS.  Simple fix.  I just allocate to forced align of 8.

But getting allocation to align to force a maximal alignment to be the same as minimal should flush out problems easier, or at least trigger warnings that force us to figure things out.

NOTE, the *_tiny() allocations do not have this max alignment=min alignment, but I think you dropped most of those and switch to mem_alloc_align

**Comment by magnumripper** [comment]
Tiny has it since 093d04b
