### ISSUE TITLE
Add a shared get_integer() for use in valid()

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1276]
189064c adds a function that we might want to re-use in many formats. It could be moved to common.c and declared in common.h with a line or two of "documentation" in comments.

**Comment by loverszhaokai** [comment]
I think the `get_integer()` is better than `atoi()`, since `atoi()` does not return error.
So all the most of the `atoi()` should be replaced ? 
**Is there any case that we can not replace `atoi()`** ?

**Comment by frank-dittrich** [comment]
In common.c, we also have functions like isdec(), isdecu() and isdec_negok().
These funcitons also call atoi() or atou(), but these funktions verify the result, i.e., they don't rely on undefined behavior.

That's why, I think functions using atoi() don't need to be changed if they verified the strings with isdec() or isdec_negok() first.

**Comment by magnumripper** [comment]
See also https://github.com/magnumripper/JohnTheRipper/commit/189064ccf97b23b520409cf7674b6a7a97d435b4#commitcomment-11120737

**Comment by jfoug** [comment]
We could to something like:

int get_sinteger(char **in_out_str, int *val);
int get_uinteger(char **in_out_str, unsigned *val);

Then we can use these functions for both valid and binary/salt or wherever needed.  Do the validation, pointer increment and value filling in one simple function.

Yes, the idec(), isdecu() ishex(), etc have made writing a good valid() function simpler, but they do not help the other consumer functions

**Comment by magnumripper** [comment]
@jfoug isn't (a variation of) this implemented now?

**Comment by jfoug** [comment]
yes
