### ISSUE TITLE
Dynamic format should honor --disable-openmp-for-fast-formats (which is now default)

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1334]
Basically, this is all that's needed (in the right places in dynamic source files)
```
#if !FAST_FORMATS_OMP
#undef _OPENMP
#endif
```

It would be cool if this could be set per dynamic subformat, but I reckon that would be far too complex.

**Comment by jfoug** [comment]
Was a little more difficult. I 'have' to remember that we are in an OMP build, even if not using OMP, because the MD5_body that is build in md5.c is MD5_body_for_thread()  The MD5_body() function is only build on non-OMP builds.  Dyna uses this function for all non SSE work, so the proper function has to be used. 

The long and short is dyna now honors the FAST_FORMATS_OMP flag, BUT the build is not the same as you would get in a true non-OMP configure.

**Comment by jfoug** [comment]
The patch will be redone. I was not aware that --disable-openmp-for-fast-formats was default.  So my testing was not adequate.  The patch would disable openmp always.  I am fixing that.

**Comment by jfoug** [comment]
ee987a8 is correct fix.

**Comment by magnumripper** [comment]
I'm afraid this have side effects
```
john.c:62:12: warning: 'john_omp_threads_orig' defined but not used [-Wunused-variable]
 static int john_omp_threads_orig = 0;
            ^
john.c:63:12: warning: 'john_omp_threads_new' defined but not used [-Wunused-variable]
 static int john_omp_threads_new;
            ^
```
I haven't looked but I reckon john.c includes dynamic.h and thus gets _OPENMP undefined. That's not good! I'm not sure what to do about it... maybe dynamic.h must not do that, only the .c files.

**Comment by jfoug** [comment]
3e0b41d should correct this, taking this check out of the headers.  The concern I had is there are structures which depend upon this being right (i.e. OMP will change the look of the structure). BUT I do not think that will cause any problem at least within john.c

**Comment by magnumripper** [comment]
We now have segfaults in clang builds: https://travis-ci.org/magnumripper/JohnTheRipper/jobs/63413606

**Comment by magnumripper** [comment]
Note: clang builds are non-OpenMP

**Comment by jfoug** [comment]
It is due to md4 being PARA 4.  I can replicate if I make MD5 para 5 md4 para 4 and sha1 para2.  I bumped up the NON_OMP_MAX from 840 to 1680 (x2) and the core goes away.  I thought I had enough factors of 2 in 840, but obviously not.  Now there are 2^4*3*5*7  I think this should handle all para combinations up to PARA=7

**Comment by jfoug** [comment]
The cores had nothing to do with this issue.  It had to do with changes for #1127

**Comment by jfoug** [comment]
I believe this is now complete.  I did not close, due to Travis failures, then failures on 32 bit builds.  Both of those are now working fine, and I think this is implemented properly now.

**Comment by magnumripper** [comment]
All systems go
