### ISSUE TITLE
x86-64 non-SIMD build

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1370]
After 11e2ee99c I can build x86 64-bit without SIMD like this:
```
./configure CPPFLAGS="-mno-sse2" --disable-cuda --disable-opencl &&
sed -ri 's/ x86-64.o sse-intrinsics.o//' Makefile &&
make -s clean && make -sj4
```
I needed to edit Makefile and drop x86-64.o and sse-intrinsics.o from JOHN_OBJS. We should fix autoconf so this isn't needed. I'm pretty sure we can use x86-any.h even for 64-bit builds.

**Comment by jfoug** [comment]
Please check out the config changes.  See if it is enough.

**Comment by jfoug** [comment]
I tried adding -mno-mmx to the 64 bit build, but gcc fails to build if there is no MMX.  NOTE, on cygwin64, gcc fails to build if SSE2 is not defined.

I am leaving the -mno-mmx test in configure (the 2nd change), since there may be ability on some compilers to do it.  But for now, on linux we can test a non-sse2 build simply using the configure with "CPPFLAGS=-mno-sse2"

**Comment by magnumripper** [comment]
It works just fine on OSX too. And no warnings or failures from a non-SIMD build.
