### ISSUE TITLE
Dynamic questions

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1482]
```
[List.Generic:dynamic_1029]
Expression=sha256($pass) (first 32 bytes)
Flag=MGF_FLAT_BUFFERS
MaxInputLen=110
MaxInputLenX86=110
Func=DynamicFunc__clean_input
Func=DynamicFunc__append_keys
Func=DynamicFunc__SHA256_crypt_input1_to_output1_FINAL
Test=$dynamic_1029$e4ad93ca07acb8d908a3aa41e920ea4f:iloveyou
Test=$dynamic_1029$13b1f7ec5beaefc781e43a3b344371cd:freedom
Test=$dynamic_1029$aa97302150fce811425cd84537028a5a:computer
Test=$dynamic_1029$75ff6bea5b0ad25171988e435c24b3ee:12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
```
1. Is there a reason we're not allowing lengths up to 64+55 == 119?
2. What does "first 32 bytes" mean? The test hashes seem truncated at 16 bytes (hex length 32), is that it? That's very confusing, especially considering normal sha256 output is indeed 32 bytes.
3. And what in the script above makes for that truncation? Is this actually a limitation and we can't produce full output? Or what would a bog standard sha256($p) script look like?

**Comment by jfoug** [comment]
Dyna simply had had a 110 byte limit forever, and I do not plan on changing. Btw, 119 kicks up 64 byte sha to 2 limbs.

The implied input Len for dyna is 32 hex bytes. That can be changed with MGF flags. in this format there are no flags, so 32 byte hex will be valid. This has and others were built because a user had a huge set of raw hashes, all 32 byte hex but many were truncations of bigger hashes

**Comment by magnumripper** [comment]
> Dyna simply had had a 110 byte limit forever, and I do not plan on changing. Btw, 119 kicks up 64 byte sha to 2 limbs.

Ah yes SHA-512 can do up to 111 or something in one limb. This is all fine, I was just curious.

> The implied input Len for dyna is 32 hex bytes. That can be changed with MGF flags. in this format there are no flags, so 32 byte hex will be valid.

OK. I think we should change these strings to say "first 32 hex chars" or something, it's very confusing now.

**Comment by jfoug** [comment]
Up to this point, I really have not tracked/modified dynamic.conf for other users input, other than to do some optimizations where others are not aware of faster ways of doing things (MGF_SALT_AS_HEX type optimizations).

I can easily change this, but is this any less confusing than what it is today?  Normally, we would add a flag for sha256 final hash to say only use valid hashes that are 32 bytes long (64 hex bytes).  Here we do not add that flag and dyna uses the default 16 byte input (32 byte hex).  These really are not all that useful ITW, other than people having a collection of 32 byte hex strings, and wanting to crack as many as possible.  There may be a system out there, which also truncates (space savings in some DB).  So they may actually use some hash like pbkdf2-hmac-sha512, but only store 16 bytes of the hash calling that 'good enough'.  In that case, we would need something like this, since we really do not know or care about the other 48 bytes of data.  Something like this may happen if a company updates their hashing function from some md5 to a better hash, but they have to continue to allow the older hashes to work.

But back to the issue.  If you think it is confusing, then go ahead and change it. If so, then we may want to track changes to dynamic.conf a little closer, so that they conform with whatever 'standard' we deem it should be (like the $salt vs $s issue).

**Comment by magnumripper** [comment]
Yeah I will. IMO "first 32 hex chars" is not very ambiguous while "first 32 bytes" is not only ambiguous but also very misleading.
