### ISSUE TITLE
Document the new self-described dynamic format

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1503]
No hurry, just adding an issue so we don't forget.

We should have a list of all valid "functions" like uc() and sha384(), and "variables/constants" like $p, $u, $c and so on.

**Comment by jfoug** [comment]
> and sha384()

These are growing by about a hundred or so, today, lol.  I am in the process of adding ALL haval hashes (5 lengths, with 3 iteration counts, so 15 in total).  I am also going through ALL of dynamic, and setting it up using #define macros.  So now i do things like this:

```C
#define LEXI_FUNC(N,T,L) \
	static void dynamic_f##N##h()    { dyna_helper_pre(); T##_hex();               dyna_helper_poststr(); } \
	static void dynamic_f##N##H()    { dyna_helper_pre(); T##_hex(); strupr(h);    dyna_helper_poststr(); } \
	static void dynamic_f##N##6()    { dyna_helper_pre(); T##_base64();	           dyna_helper_poststr(); } \
	static void dynamic_f##N##c()    { dyna_helper_pre(); T##_base64c();           dyna_helper_poststr(); } \
	static void dynamic_f##N##r()    { dyna_helper_pre(); T##_raw();               dyna_helper_post(L); }
LEXI_FUNC(5,md5,16)       LEXI_FUNC(4,md4,16)          LEXI_FUNC(1,sha1,20)
LEXI_FUNC(224,sha224,28)  LEXI_FUNC(256,sha256,32)     LEXI_FUNC(384,sha384,48)  LEXI_FUNC(512,sha512,64)
LEXI_FUNC(gost,gost,28)   LEXI_FUNC(tig,tiger,24)      LEXI_FUNC(wrlp,whirlpool,64)
LEXI_FUNC(rip128,ripemd128,16) LEXI_FUNC(rip160,ripemd160,20) LEXI_FUNC(rip256,ripemd256,32) LEXI_FUNC(rip320,ripemd320,40)
LEXI_FUNC(hav128_3,haval128_3,16) LEXI_FUNC(hav128_4,haval128_4,16) LEXI_FUNC(hav128_5,haval128_5,16)
LEXI_FUNC(hav160_3,haval160_3,20) LEXI_FUNC(hav160_4,haval160_4,20) LEXI_FUNC(hav160_5,haval160_5,20)
LEXI_FUNC(hav192_3,haval192_3,24) LEXI_FUNC(hav192_4,haval192_4,24) LEXI_FUNC(hav192_5,haval192_5,24)
LEXI_FUNC(hav224_3,haval224_3,28) LEXI_FUNC(hav224_4,haval224_4,28) LEXI_FUNC(hav224_5,haval224_5,28)
LEXI_FUNC(hav256_3,haval256_3,32) LEXI_FUNC(hav256_4,haval256_4,32) LEXI_FUNC(hav256_5,haval256_5,32)
```

Adding a new hash simply consists of adding a new LEXI_FUNC() with proper items.  There are about 6 or 7 of these type things in the compiler, about 6-8 in dynamic_fmt.c, many in the parser, some in dynamic.h  and probably MANY in dynamic_preload.c  I would REALLY like to clean this up, so that adding a new hash is simply adding a line in about 20 places in the code an rebuilding.  I already have that for the big_crypt code.  In that code, I add one line to a .sh file, and I get the 'real' file. The others are not the real deal, the CPP will  actually generate them.  It does not make for easy debugging, BUT once things are worked out, all the macro declarations should be working.  IF there is something needing debugged, we can always comment out a macro define, and expand the 'real' code, debug, then when fixed, put the macro back.

I hope to have this checked in tonite.  Once that is done, extending dyna should be childs play.

**Comment by jfoug** [comment]
Should this be a stand alone document (my choice), or tied into the existing DYNAMIC readme files?

**Comment by magnumripper** [comment]
I agree a stand alone new one is better.

**Comment by jfoug** [comment]
9a93a71
