### ISSUE TITLE
Reverse steps in shared SIMD functions

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1523]
Since 6a0f06466 we have a SSEi_REVERSE_STEPS flag for our shared primary hash functions. For MD4 it's real reversing of steps, and used in the NT format. It does exactly the same reversing as Alain's NT assembler format. For MD5, SHA1 and SHA2 formats, it merely skips the final addition of constants.

- [x] MD4 function
- [x] raw-md4 format
- [x] NT format
- [x] MD5 function
- [x] raw-md5 format
- [x] SHA1 function
- [x] raw-sha1 format
- [x] MSSQL format
- [x] MSSQL05 format
- [x] SHA256 function
- [x] raw-sha256 format
- [x] SHA512 function
- [x] raw-sha512 format
- [x] MSSQL12 format

```- [ ] dynamic formats?   (Not likely going to happen, jfoug)```

**Comment by jfoug** [comment]
I changed the dyna to not do this. I really do not see this as a viable option in dyna.  It would add a major complexity issue, and for what ROI?  Already dyna is NOT the fastest horse in the stable, no matter what, since there is other overhead involved. So making an already slower format a little faster but still slower is not really worth it, especially if it opens up another set of instability issues and drags on any form of forward development until these new issues are addressed.

I have 'commented it out'.  It no longer shows on the count of todo items.

**Comment by magnumripper** [comment]
Yeah that makes sense. And the SHA2 formats that remain will probably show insignificant gain. The real win here was the NT format. The recent AVX2 support was a major blow to Alain's format (now "nt-old") and this fix was another one: Now the intrinsics NT format should be faster on any SSE2 or better build.

**Comment by magnumripper** [comment]
Damn, I just tested a build with only SSE2 and Alain's format is still 2.5% faster than the intrinsics one. Probably due to the stacks of `if` that handles all SSEi flags... But when building with AVX we outrun it anyway and with AVX2 we obviously run in circles around it.

**Comment by magnumripper** [comment]
48c80a4 improves SHA1 reversing for a 5% boost.
