### ISSUE TITLE
dynamic_1401 and dynamic_1506 claim salt size 0, but have "Many salts" benchmark

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1611]
```
(bleeding-jumbo)run $ ./john --list=format-all-details --format=dynamic_1401
Format label                         dynamic_1401
 Disabled in configuration file      no
Min. password length in bytes        0
Max. password length in bytes        23
Min. keys per crypt                  1
Max. keys per crypt                  3360
Flags
 Case sensitive                      yes
 Supports 8-bit characters           yes
 Converts 8859-1 to UTF-16/UCS-2     no
 Honours --encoding=NAME             no
 False positives possible            no
 Uses a bitslice implementation      no
 The split() method unifies case     yes
 A $dynamic$ format                  yes (Interleaved SIMD)
 A dynamic sized salt                no
Number of test vectors               24
Algorithm name                       md5($u.\nskyper\n.$p) (Skype MD5) 256/256 AVX2 8x3
Format name                          
Benchmark comment                    
Benchmark length                     0
Binary size                          16
Salt size                            0
Tunable cost parameters              
Example ciphertext                   username:$dynamic_1401$27f6a9d892475e6ce0391de8d2d893f700000000

(bleeding-jumbo)run $ ./john --test --format=dynamic_1401
Benchmarking: dynamic_1401 [md5($u.\nskyper\n.$p) (Skype MD5) 256/256 AVX2 8x3]... DONE
Many salts:	9229K c/s real, 9323K c/s virtual
Only one salt:	7842K c/s real, 7842K c/s virtual

```
Same for dynamic_1506

**Comment by jfoug** [comment]
This is due to how the salt size display is done for dynamics. That code drills down into the dynamic format, since the 'outside' format structure always says salt size is sizeof a pointer.

But if the format does NOT have a SaltLen value, then it is outwardly viewed as 0 bytes.

I will try to get this fixed in a generic manner.  What I may do is simply exit john during the dynamic initialization with an error, when a format is attempted to be inialized that is a salted format, but with salt-len==0 and exit with a proper error message, somthing like "dynamic_xyz is a salted format but the SaltLen was not set properly within the format".  That will force anyone writing a script to get them right.  The dyna-compiler will always have a SaltLen, btw.

**Comment by jfoug** [comment]
I have made some changes to dynamic_fmt.c   It will now fail to load a hash if at the end of the processing loop, the size of salt (on a salted hash) is at 0.  There are formats where salt length can be determined.  These formats listed here, it can not and requires the user to properly enter that value.  This is what would be output (prior to my fixing dynamic.conf) with the change doing a -test=0 for -format=dynamic-all

```
 $ ../run/john -test=0 -form=dynamic-all
Error invalid format dynamic_1401 md5($u.\nskyper\n.$p) (Skype MD5)
        It is required to add SaltLen= to the script, for this format
Error invalid format dynamic_1506 md5($u.:XDB:.$p) (Oracle 12c "H" hash)
        It is required to add SaltLen= to the script, for this format
Testing: dynamic_0 [md5($p) (raw-md5) 128/128 XOP 4x2]... PASS
Testing: dynamic_1 [md5($p.$s) (joomla) 128/128 XOP 4x2]... PASS
....
```
