### ISSUE TITLE
New john.conf variable to prevent overwriting existing .rec file

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1635]
Default should be N, to keep current behavior.
Max be we even need 3 values:
-ignore existing .rec files when starting a new session
-when using --session=, don't allow names that cause overwriting of existing sessions
-never overwrite an existing .rec file, not even the default john.rec

**Comment by jfoug** [comment]
Here is what I would recommend.  I will start on this, so speak up now if this is not what you had in mind, or if you wanted less/more.

```
[Options]
RestoreFileProtect=XXXX

XXX will be:
    Ignore     (default behavior.  no check is done, files simply are overwritten)
    Named    (do not allow overwriting of -session=Named files)
    Always    (do not allow overwriting of any .rec file)
```

Since default is to not protect the files, I am not worried about adding another un-needed command line switch.  If you change the behavior by putting it on Named, then you will be smart enough to know how to remove it if you want the overwrite behavior back.

**Comment by jfoug** [comment]
I think I am going with "Disabled"  "Named" and "Always"  Since disabled seems to read more clearly with the option name.

**Comment by frank-dittrich** [comment]
Yes, that's exactly what I want, and of course, a john.conf variable is OK, I didn't want yet another option...

**Comment by magnumripper** [comment]
We call that file the "session file" elsewhere, so I think it should be SessionFIleProtect.

I like the "Disabled" "Named" and "Always".
