### ISSUE TITLE
Add Unicode support to External mode 

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1641]
As listed in #1632 support has to be added here also.

**Comment by magnumripper** [comment]
External mode is kind of special because we use `word[]` to hold the word and that's actually an int array. So with just a little extra code we could allow UTF-32 and do a quick conversion to target encoding right when calling `crk_process_key()`.

This would mean that the "dumb16" and "repeats16" modes would work without their filter (and probably be much faster).

**Comment by magnumripper** [comment]
Implemented in 8960d1fd
