### ISSUE TITLE
Document how to build a fallback chain of john binaries with different CPU features

### ISSUE THREAD

**Issue by rhertzog** [magnumripper/JohnTheRipper#1656]
Hello, I know that john has some system to exec another binary with less CPU features if the current binary turns out to be not adapted for the current CPU (mentioned in #914 too). The Debian package makes use of this. In kali we use the jumbo version with its autoconf based build framework and I just don't know how I can achieve the same... thus it would be nice if this could be documented somewhere. I did not find anything in the "docs" directory.

Right now we're forced to build the package without auto-detection of CPU features, otherwise we get reports such as this one: https://bugs.kali.org/view.php?id=2498

Thank you!

**Comment by magnumripper** [comment]
That stuff is not much tested (if at all) with autoconf. For a distro, it might be better just using the legacy Makefile, and similar procedure as non-Jumbo (the "docs" are more or less just comments in params.h).

Eventually, an autoconf build should automagically build all fallback binaries but since neither of the developers need/use this, I'm afraid it's low priority.

**Comment by magnumripper** [comment]
This should be added to #1475

**Comment by magnumripper** [comment]
We have [some interim docs](https://github.com/magnumripper/JohnTheRipper/wiki/Fallback-binary-chains) now.
