### ISSUE TITLE
Change PHPASS format to thick

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1672]
http://www.openwall.com/lists/john-dev/2015/08/16/16

We had a thick format long ago, but it predated our Git history. I can probably be dug out of some old Jumbo tarball and refurbished.

**Comment by jfoug** [comment]
6c3053e is fat PHPASS.  BUT it still needs 'lots' of love.  I did get it to at least compile and run.

The format structure from where i started was old (even pre source(),  v8 ?).   I put in hard constants for  binary align and salt align.  Those will need to be looked at.  Also, I put in null for the tunable cost stuff, and there certainly is tunable costs (iterations).

All of the SIMD code will not build at the current time. If the defines (MMX_COEF) are changed to SIMD_COEF_32, it still will not build, because it was written to use the mmx.S file which no longer exists.  This will need to be properly ported to intrisic SIMD code, and made to work with SIMD_COEF_32 larger than 4.   But what is there is a very good start.  It should not take too much to get this fat format working properly again.

**Comment by magnumripper** [comment]
Current code warnings
```
phpassMD5_fat_fmt_plug.c: In function 'phpassmd5_set_salt':
phpassMD5_fat_fmt_plug.c:184:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   ((ARCH_WORD_32 *)cursalt)[0] = ((ARCH_WORD_32 *)salt)[0];
   ^
phpassMD5_fat_fmt_plug.c: At top level:
phpassMD5_fat_fmt_plug.c:490:5: warning: initialization from incompatible pointer type
     phpassmd5_crypt_all,
     ^
phpassMD5_fat_fmt_plug.c:490:5: warning: (near initialization for 'fmt_fat_phpassmd5.methods.crypt_all')
```

**Comment by jfoug** [comment]
The code as submitted builds and works. it is not done.  I thought @zzlei was working on this one?  I just put a fat format back into code.  The SIMD code needs to be re-done, using intrisics, and it also needs to make sure it works for SIMD_COEF_32 > 4

Yes, there are warnings. Keep in mind, the code was 3.5 years old, and found in unused, so I am not sure how long since it was actually 'used'.

**Comment by zzlei** [comment]
I haven't started working on it yet. I need to finish my work on 7z first.

**Comment by jfoug** [comment]
I can easily get this one done (I think).  I wrote it from the beginning, and it was one of my first SIMD projects.  Should be pretty trivial to get it as fast (or faster) than dynamic, and then have it properly OMP.

**Comment by magnumripper** [comment]
I wasn't complaining, just documenting in case some compilers don't show them :-)

**Comment by jfoug** [comment]
Getting close.

on my avx2:  4-HT

dyna_17:  60k
starting_fat:  4k  (oSSL, no OMP)
AVX2_fat_omp:  261K  (if run OMP=4  238K)

I am still getting cores under some conditions.

in VC, non-SIMD and SIMD both work (have not tested with OMP).

On XOP, non-SIMD working, but only without OMP.  SIMD working, but only WITH OMP.

Probably some very trivial things, I just have to find them.

This version will split/prepare $dynamic_17$ into $P$ format.  I would like to also scrub dynamic_17 from dynamic. It is a bunch of exceptional code, and removing it would help and does not impact any other hash type.  But first I need to get this one done.

**Comment by jfoug** [comment]
Ok, the only thing I have left now, is OMP non-SIMD. All else works, including SIMD_COEF_32 > 4

Pretty much re-wrote the format. This thing really rocks now.  This was the original format I did for john, 6 years ago.  I had code written to find md5 raw hashes from my phpbb database (converting some older users, while keeping their passwords if they ever logged back in).  I then found the algo for the $P$ hash, and wrote that.  But then found john, and the raw-md5 there blew away what I had.  BUT john did not do $P$.  Now I thought that strange, since Solar was the designer of the phpass algorithm, which the Phpbb boys used.  So I ported my code (which was about 1k/s) to a oSSL format for john, then figure out how to do the SIMD stuff (took a long time). I got it up to 8k/s I think.     Now, it is over 260k/s.  Quite an improvement for a CPU format.

I should get this in shortly.

**Comment by jfoug** [comment]
Wow, bonehead reason why OMP non-SIMD was failing.  ctx was a static, lol.

Just a bit of testing, and should get this format in.

**Comment by jfoug** [comment]
I think I can stick a fork in this problem.  (well I still have to scrub dyna_17 from our memory)

```
$ ../run/john -test=4 -form=phpass-md5
Will run 4 OpenMP threads
Benchmarking: phpass-md5 [phpass-MD5 128/128 XOP 4x2]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 2048
Raw:    30368 c/s real, 8754 c/s virtual

 $ OMP_NUM_THREADS=1 ../run/john -test=4 -form=phpass-md5
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Benchmarking: phpass-md5 [phpass-MD5 128/128 XOP 4x2]... DONE
Speed for cost 1 (iteration count) of 2048
Raw:    14332 c/s real, 14313 c/s virtual

 $ ../run/john -test=4 -form=dynamic_17
Benchmarking: dynamic_17 [phpass ($P$ or $H$) 128/128 XOP 4x2]... DONE
Raw:    14108 c/s real, 14068 c/s virtual
```

It is amazing.  My 4 core HT AVX2 is almost 10x faster than my 2 core-HT XOP machine.  XOP really helps out SHA1 and SHA2 functions. But not so much for MD5.  That AVX2 just literally screams!

**Comment by jfoug** [comment]
It is now 100% 'done'.  The format should be the same as it was (interface wise).  Same strings, same label, and same 'name' for the source file name.

One thing I do need to do, is to log into my work box, and make sure I did not fuxor something up on BE builds, lol.
