### ISSUE TITLE
Unify case in dynamic names

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1717]
```
$ ../run/john -list=subformats | awk '{print $7}' | cut -d\( -f1 | sort -u | xargs echo | column -t | fold -s
Cisco  GOST  HAVAL128_3  HAVAL128_4  HAVAL128_5  HAVAL160_3  HAVAL160_4  
HAVAL160_5  HAVAL192_3  HAVAL192_4  HAVAL192_5  HAVAL224_3  HAVAL224_4  
HAVAL224_5  HAVAL256_3  HAVAL256_4  HAVAL256_5  KECCAK_256  KECCAK_512  MD2  
PANAMA  PeopleSoft,  RIPEMD128  RIPEMD160  RIPEMD256  RIPEMD320  SHA3_224  
SHA3_256  SHA3_384  SHA3_512  SKEIN224  SKEIN256  SKEIN384  SKEIN512  Tiger  
WHIRLPOOL  Whirlpool  md4  md5  sha1  sha224  sha256  sha384  sha512
```
IMHO the above hurts the eye. This looks much nicer:
```
$ ../run/john -list=subformats | awk '{print $7}' | cut -d\( -f1 | tr A-Z a-z | sort -u | xargs echo | column -t | fold -s
cisco  gost  haval128_3  haval128_4  haval128_5  haval160_3  haval160_4  
haval160_5  haval192_3  haval192_4  haval192_5  haval224_3  haval224_4  
haval224_5  haval256_3  haval256_4  haval256_5  keccak_256  keccak_512  md2  
md4  md5  panama  peoplesoft,  ripemd128  ripemd160  ripemd256  ripemd320  sha1 
sha224  sha256  sha384  sha3_224  sha3_256  sha3_384  sha3_512  sha512  
skein224  skein256  skein384  skein512  tiger  whirlpool
```

I suppose this is just cosmetic and would involve an overhaul of dynamic_preloads.c and the dynamic*conf files? @jfoug I put you as assignee because you 'own' dynamic. I can do this if you thinks it's a silly and unneccessary idea :smile:

**Comment by magnumripper** [comment]
BTW another irregularity is eg. `sha384` and `skein224` vs. `keccak_256`. Perhaps the keccak's should drop the underscore?

**Comment by jfoug** [comment]
If I could do things over again, I would have sha384 be changed to sha2_384, since the sha3 stuff IS clashing. However, almost everywhere you 'look', you do see sha384.

keccak_256 is somewhat standard.  Perl does the same thing.  Same for sha3_256, etc.

I am handing the -list=subformats by itself.  There is a singular function that does the outputting. I am just strlwr within that function.  This will NOT adjust what is shown when actually 'running' john.

What are your expectations here?

**Comment by jfoug** [comment]
I am going to check in my lc() for -show=subformats.  If you dont like it or want more, I will do it.

**Comment by magnumripper** [comment]
Ah, that was easy, lol. Thanks!

**Comment by jfoug** [comment]
Now, this only 'fixes' the -list=sub output, nothing else.  If that is all that you were wanting, then this one is done.

**Comment by jfoug** [comment]
Surprisingly much in dyna is not all that hard. However, there is SOOO much stuff, that finding just the tiny thing can be hard at times.  And there is some stuff that is a nightmare (some of the size detectsions and status type crap).  That is the part of dyna that I cringe when I have to work on it, and I really hate going back and finding problems because some change broke things in strange places but were not caught at the time of the change.

**Comment by magnumripper** [comment]
Unfortunately things like `md5($u.:XDB:.$p) (Oracle 12c "H" hash)` are now shown with "XDB" lower-cased. That's not very good. I think I'll bite the bullet and edit all definitions instead.

**Comment by jfoug** [comment]
This reverts https://github.com/magnumripper/JohnTheRipper/commit/5ca823a35a888cf99a1581827b9e71a649911697  and changes case.  It actually was easy.  Was done with macros to add the large hashes. 'most' of the code (i.e. other macros) required upper cased naming of the variables.  However, this macro param was used ONLY for the format name string, thus was very safe to change.  Then had to fix a couple hold overs in dynamic.conf and it is wrapped up.  We still maintain Capital letters in other parts of the expression 'string', after the expression.
