### ISSUE TITLE
Large alignments on stack (eg. AVX2)

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1735]
See also #1731 and http://www.openwall.com/lists/john-dev/2015/09/06/5

Perhaps write an autoconf test that can safely detect whether large stack alignments (i.e. MEM_ALIGN_SIMD for AVX2 and above) work, and if so set SAFE_ALIGN_SIMD or whatever macro. This means we can optimize things currently always using `mem_align()`, especially in pseudo_intrinsics.h and simd-intrinsics.c.

Actually we could already set that macro for any build where sizeof(vtype) <= 16.

**Comment by magnumripper** [comment]
The AC test need to be very thorough though. I think we've sometimes seen problems surface only under OMP.

**Comment by jfoug** [comment]
This was posted as a line comment

https://github.com/magnumripper/JohnTheRipper/commit/1bd8d9dc2ccad29db96f424a89e3a51153972fb5#commitcomment-13086395

This is the way to go, not to probe.

**Comment by jfoug** [comment]
Think I found the problem.  There was a #undef mem_align at bottom of pseudo_intrinsics I missed.

**Comment by jfoug** [comment]
Think I found the problem, I was getting crashes. I have to typecast a to unsigned char before doing the -1

Finally got it (glad I wrote a 'test' app, lol)

**Comment by jfoug** [comment]
here is the test:

```
#include <stdio.h>
void *mem_align(void *a, int b) {
	char *al = (char*)a;
	al += (b-1);
	al -= (size_t)al&(b-1);
	return al;
}
#define mem_align_define(a,b) (void*)( ((char*)(a))+( ((b)-1) - (((size_t)((char*)(a))-1)&((b)-1))))

int test1(), test2(), test3();
int main() {
	if (test1() && test2() && test3())
		printf ("success\n");
}
int test1() {
	unsigned char buf[256];
	int i;
	for (i = 0; i < 16; ++i) {
		if (mem_align(&buf[i], 16)-(void*)&buf[i] != mem_align_define(&buf[i], 16)-(void*)&buf[i]) {
			printf ("Failure\n");
			return 0;
		}
	}
	for (i = 0; i < 32; ++i) {
		if (mem_align(&buf[i], 16)-(void*)&buf[i] != mem_align_define(&buf[i], 16)-(void*)&buf[i]) {
			printf ("Failure\n");
			return 0;
		}
	}
	for (i = 0; i < 64; ++i) {
		if (mem_align(&buf[i], 64)-(void*)&buf[i] != mem_align_define(&buf[i], 64)-(void*)&buf[i]) {
			printf ("Failure\n");
			return 0;
		}
	}
	return 1;
}
int test2() {
	unsigned long buf[256];
	int i;
	for (i = 0; i < 16; ++i) {
		if (mem_align(&buf[i], 16)-(void*)&buf[i] != mem_align_define(&buf[i], 16)-(void*)&buf[i]) {
			printf ("Failure\n");
			return 0;
		}
	}
	for (i = 0; i < 32; ++i) {
		if (mem_align(&buf[i], 16)-(void*)&buf[i] != mem_align_define(&buf[i], 16)-(void*)&buf[i]) {
			printf ("Failure\n");
			return 0;
		}
	}
	for (i = 0; i < 64; ++i) {
		if (mem_align(&buf[i], 64)-(void*)&buf[i] != mem_align_define(&buf[i], 64)-(void*)&buf[i]) {
			printf ("Failure\n");
			return 0;
		}
	}
	return 1;
}
int test3() {
	long double buf[256];
	int i;
	for (i = 0; i < 16; ++i) {
		if (mem_align(&buf[i], 16)-(void*)&buf[i] != mem_align_define(&buf[i], 16)-(void*)&buf[i]) {
			printf ("Failure\n");
			return 0;
		}
	}
	for (i = 0; i < 32; ++i) {
		if (mem_align(&buf[i], 16)-(void*)&buf[i] != mem_align_define(&buf[i], 16)-(void*)&buf[i]) {
			printf ("Failure\n");
			return 0;
		}
	}
	for (i = 0; i < 64; ++i) {
		if (mem_align(&buf[i], 64)-(void*)&buf[i] != mem_align_define(&buf[i], 64)-(void*)&buf[i]) {
			printf ("Failure\n");
			return 0;
		}
	}
	return 1;
}
```

It tests different sized buffers, testing each for 16, 32 and 64 byte offsets.  This test was against the functional version.

**Comment by jfoug** [comment]
Checked in here.  This issue should now be moot.

**Comment by magnumripper** [comment]
The macro is much better.
Solar described more problems though: http://www.openwall.com/lists/john-dev/2015/09/06/5

Re-opening for evaluation.

**Comment by jfoug** [comment]
If you dig more into that thread, Solar and I did talk about bit more about some of these issues. Put no code into play, but there is more ideas bouncing around, good and bad.

**Comment by magnumripper** [comment]
What you suggested in http://www.openwall.com/lists/john-dev/2015/09/06/9 is pretty slick. I'll experiment a little with that.

I wonder though, why we've only seen probems for real in a few formats and only under OpenMP. As far as I know we've **never** seen problems with explicit vector declarations that doesn't end up in registers. Maybe gcc actually handles that properly. If we can confirm that, we can use it:

Instead of:
```c
        char _b[8 * 64 * MD5_SSE_NUM_KEYS + MEM_ALIGN_SIMD] = { 0 };
        unsigned char (*buffers)[64*MD5_SSE_NUM_KEYS] =
                mem_align(_b, MEM_ALIGN_SIMD);
```

We'd just do:
```c
        vtype _b[8 * 64 * MD5_SSE_NUM_KEYS / sizeof(vtype)] = { 0 };
        unsigned char (*buffers)[64*MD5_SSE_NUM_KEYS] = (unsigned char*)_b;
```

**Comment by magnumripper** [comment]
This might be part of a canonical solution:
```diff
diff --git a/src/configure.ac b/src/configure.ac
index 0f27922..f45cd56 100644
--- a/src/configure.ac
+++ b/src/configure.ac
@@ -225,6 +225,8 @@ if test "x$asan" = xyes || test "x$ubsan" = xyes ; then
 else
    JTR_FLAG_CHECK([-fomit-frame-pointer], 1)
 fi
+   # AVX2 alignment
+   JTR_FLAG_CHECK([-mpreferred-stack-boundary=5], 1)
    # gcc bug workaround, see issue 632
    JTR_FLAG_CHECK([--param allow-store-data-races=0], 1)
    # Silly OSX warnings
```
...but there's more to it than the above. First, we should only do it for AVX2 or higher. Second, it should not always be "5" - it should be the log2 of `sizeof(vtype)`.

**Comment by magnumripper** [comment]
http://www.openwall.com/lists/john-dev/2015/09/08/14

**Comment by magnumripper** [comment]
I currently believe this is all a red herring **except** the case (that we've actually seen IRL) where we declare variables local to an OMP parallel block, and try to use `JTR_ALIGN()` (a.k.a `__attribute__ ((aligned()))`). Unless my theory is debunked we should revert most of 1bd8d9d, especially the change to `md5cryptsse()`.

**Comment by magnumripper** [comment]
@jfoug I believe your mem_align macro might actually be optimized away when needed the most:
http://www.openwall.com/lists/john-dev/2015/09/09/3

We'll see - let's remember this in case we see strange things happen.

**Comment by jfoug** [comment]
Remembered.  However, I fail to see how this every could be optimized away.  It 'may' be when  the constants used are known by the compiler to be what the stack already is aligned to, however, since all usages are against char* or unsigned* arrays, the compiler will only be aligning stack to 4 or 8 bytes, so there should be no chance the compiler runs the math, completing the expression and finding that no work is ever being done.  If it does optimize it away, it would only be done by bugs in the optimizer, or if we tried to align to 4 bytes or something.

**Comment by jfoug** [comment]
One other huge difference in using the macro is that the way the macro is used, there is always an lparam expression, where your expression was a simple read test that affected nothing in the running environment other than conditional logic.

I am a bit surprised yours was optimized away, but I do understand the optimizer wanting to optimize it away. I would just think it should not.  I bet it was optimized away, because it knew that it was always aligning stuff 32 bytes. But then comes along a library that does the stack work, not the compiler, and bam, that 'knowledge' that the compiler had is no longer correct.

I could be wrong however, and it is only due to my expression being complex enough that the current optimizer does not recognize it, and that when newer versions of the compiler are released, they improve the amount of code run simulation being done, and again think there is no reason to emit any code for this macro.

**Comment by magnumripper** [comment]
Did some more tests today. I can reliably see gcc-4.8 optimize away that test (when not in a separate function) but I have yet to see it do so with the macro. So I think we're safe.

**Comment by jfoug** [comment]
I honestly think it is NOT going to reduce the expression all the way out, simply because it is an expression that can not be fully expressed at compile time.  Now, if the compiler really got smart, and realized just what the expression was trying to do, and then stripped the emiited code down to 

buf = _buf; 

then we have problems.  I just do not see that, since I have mixed up 2 or 3 pointers, some conversion into an integer (which can NOT be known during compile), and some other stuff.  Even though the end result is a simple expression that ends up doing 
```C
buf = _buf + ((_buf+31)%32;
```
I just do not see the compiler stripping off the last part.
