### ISSUE TITLE
Document our CircleCI setup, and give access to other folks

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#1740]
Our CircleCI setup is a bit tricky to get working. I would like to ensure that the CircleCI build system is documented, and you all have access to the following parts,
- Docker image, and the ability to re-create / update it
- The small website which allows downloading Windows builds (the builds are actually stored on CircleCI systems)

**Comment by jfoug** [comment]
I see the changes, and see that it works.

Do you know just 'what' step was causing the error failure?   If we were to make a specific version that was build in a manner which a test was SUPPOSED to fail (say ONLY on a 32 bit non-SIMD build make valid always return false), would that version run and cause CircleCI to have a 'green light'.   If not, then the testing is pretty much worthless.

Also, is there any way we can externally send files to this 'small website' ?  I have a CI-like system running on a home server right now.  I am simply uploading builds to a sftp server.  I have not 'published' the location of it yet, since it's not really 'super' useful.  But if I could provide the upload data to that site, then I could have 'near realtime' and WORKING win64/win32 which we could then use as out bleeding pre-built windows binary files.

I will look your documentation over, once it is done.

**Comment by kholia** [comment]
There were multiple problems.

1. The Wine invocations were returning with 130 return code. I disabled the "exit 1" statements (which is not great), and the build could move to the next step.

2. 64-bit GCC + OpenSSL (the native stuff) itself was broken, and wasn't able to build even the simplest of OpenSSL programs. I "fixed" it my reinstalling the OpenSSL package(s).

...

I have only disabled testing of the Wine (Win64) builds. Rest of the builds (32-bit SSE2, 32-bit NON-SIMD, and NON-SIMD) still have the ```if [ "x$?" != "x0" ] ; then exit 1 ; fi``` intact. So, the CircleCI build will fail (it will *not* have a 'green light') if any of the remaining 3 builds fail testing. Hence, I am not very worried :-)

The 'small website' is running https://github.com/kholia/daily-builds/blob/master/main.py code. I don't think that we could realistically upload builds to this website. This website is running in "Google App Engine", and using more resources will cost money (I don't actually know if all this is true).

The whole point of this website is to expose the URL of the builds, which themselves reside on the CircleCI servers. The CircleCI doesn't have a way to determine / expose this URL at the moment (I have already requested them for such a feature). The code of the 'small website' is pretty simple (and will do a better job of explaining it's own purpose) :)

**Comment by jfoug** [comment]
This would be just fine.  I could host the files, and if we can modify this python script (which simply sounds like a DNS server to me), to the proper url on my box, then all is done.

What I do is have a script that monitors github. When it sees  no change, it just sleeps.  When there is some change, it simply scripts out a git pull, then make distclean, ./configure and make.  Then it zips things up and uploads.  It then does a 2nd build that is only SSE2  (first one I did was XOP).  I may also make a 3rd build that is AVX2, but that one will be done on a different box. 

This is all just running in a cygwin window.  I really should 'hide' it with the always-up service building program, but it would cause heartburn whenever I need to update cygwin (i.e. a hidden shell that I forget about).

But the files I am building are 100% working, built with cygwin.  I have a 'static' zip file (larger), that is all of the stuff that does not change (like the cygwin DLL's needed).

But if we can 'fix'. this py code to serve back a different URL, we may be golden.

**Comment by jfoug** [comment]
This conversation may be better under the 'Windows pre-build' issue thread or at least have them link to each other

#1378

**Comment by kholia** [comment]
We could 'fix' the Python code right now ;)

Here are some questions,

1. What does the naming scheme for the builds look like? We need to decide that. My new Python code will get a short git revision number from the GitHub repository (i.e. this repository), and then will use the naming scheme's knowledge to derive the actual URL (to the build residing on your box).

2. It seems that commit 5cbed9dff434376eeb5cc3b4f5547aedc873e264 did something weird (changed the 'small website' URL to point to a sftp URL, weird) but this will get resolved soon I guess.

**Comment by jfoug** [comment]
I think I did that change. That was my original start.  At this time, I have a 'universal' server, that could dish out the same files using sftp, https, or whatever we wanted.

I use somewhat the same name convention, BUT unfortunately since my built tool snapshots (only checks every 15 minutes (or once an hour, I cant remember), AND it take a while to upload, that it may not be the current version, but might be a couple behind.  But you could probably figure that out with the python script, but getting an https head on the url, working backwards on git revisions, until one worked.

I will be leaving work in an hour or so. Let me update you with the actual URL naming. There is more than 1 URL however.

**Comment by kholia** [comment]
Cool :+1: 

The Python code already has tricks to handle slow uploads (and to go back to previous builds).

**Comment by jfoug** [comment]
Ok, here is the specifics.

right now there are 3 files.

https://45.33.2.252:2443/JtR-sse2-gitid.zip
https://45.33.2.252:2443/JtR-xop-gitid.zip
https://45.33.2.252:2443/JtR-win64-base.zip

The 3rd file is a 'common' file. The user only should download it one time (there may be updates rarely).  The other 2 get built, tested, and if all goes well, zipped and uploaded.  Again, I do this on a timed basis, so I certainly may miss updates. The granularity of the sleep is only 120s however.  BUT the longest gap is during the build.  This is single threaded, does 2 configures and builds, and on cygwin, so it is NOT fast.  It's about 15 minutes for the 2nd build to get uploaded.

The script had not been running since when I installed Win10 on this box (a couple days back).  I just started it up, and this first run shows the timings:

$ ./win-pkg-make.pl
From git://github.com/magnumripper/JohnTheRipper
   7c2d0b4..a6449c5  bleeding-jumbo -> origin/bleeding-jumbo
 * [new branch]      cpp-intrinsics -> origin/cpp-intrinsics
 * [new branch]      descrypt-opencl-test -> origin/descrypt-opencl-test
Starting run on version a6449c5 at: Wed, Sep  9, 2015  6:44:38 PM
file JtR-sse2-a6449c5.zip has been created
file JtR-xop-a6449c5.zip has been created
Completed run on version a6449c5 at: Wed, Sep  9, 2015  7:03:18 PM

The IP should be static.  If we want other 'types' of builds, I can do them.  However, I have not  been able to get cygwin to do good cross compiles. I would think an acceptable set would be SSE2, XOP and AVX2  I really think there is little reason for AVX, it does not really provide a 'huge' gain over SSE2 unfortunately. But XOP provides a heck of a good gain (at least I have seen that).  Wider SIMD of course, kicks but :)

**Comment by jfoug** [comment]
I do not have a cleanup cron script running on the server at this time, and have been doing it by hand every once in a while.  The downloads are only a little over 2mb, so it really has not been a big deal (yet).  The 'common' file is bigger > 30mb   But again, it only needs to be pulled 1 time.

**Comment by jfoug** [comment]
I can easily alter packaging if people think I should.  However, it will make downloads larger.    I do have only 3000GB of monthly xfer before I get charged for more, so I have to be very careful :stuck_out_tongue_closed_eyes:

**Comment by magnumripper** [comment]
If I click the download button, I get a page with... the download button as a pic. It this just me?

**Comment by jfoug** [comment]
We will need to reset README.md  I was toying around with it a while back. I could not get it working with my server under sftp, and never got back to it.  Sounds like @kholia has a python script that acts as the DNS to find the right file(s) to download and forwards the browser to that link, so I think we can get it setup shortly.

**Comment by kholia** [comment]
@jfoug http://daily-builds.appspot.com/latest now results in downloading a 7-byte file from your box.

E.g. http://45.33.2.252:2443/JtR-sse2-39aad6f.zip

Can you please check if the builds are being properly generated on your box?

**Comment by jfoug** [comment]
I will validate the problem when I get home.

You might start out with the 'fixed' named file (the common file). Once we get that working, then we can work on the 'current' build version.

**Comment by kholia** [comment]
Have a separate "base" file might be problematic for the end-users. How is it even going to work? From which page are we going to link to the 3 files (per build) which your box has?

It is possible to generate a single unified zip (containing "john-sse2.exe" and "john-xop.exe")?

**Comment by jfoug** [comment]
That is actually my 'plan'.  Note, my AVX2 box has become stable, so I 
may switch over to turn it into the build machine. On that box, I think 
I could make 3 exe files, (avx2, xop and sse2), then package everything 
up and transmit it in a single package.

Then we could have a simple name, such as john-bleeding-win64-gitid.zip

It would likely be faster built also, since that machine runs cygwin 
(the shell commands, etc) about 4x faster than this laptop.

Let me spend a bit of time seeing about setting it up to work that way, 
and get you the naming convension.

But as a start, are you able to download the 'fixed' file properly?

**Comment by kholia** [comment]
Click on http://daily-builds.appspot.com/latest URL. I can download the files, but they are 7 bytes in length!

Even http://45.33.2.252:2443/JtR-win64-base.zip is 7 bytes! WTF? :)

**Comment by kholia** [comment]
Your 'plan' sounds great :+1:

**Comment by jfoug** [comment]
https dude.  BIG difference

**Comment by jfoug** [comment]
I wonder if we should also make some non-OMP build ?

I plan on using 'extra' exe files from the sse2 build.  Also, the john.exe WILL be sse2. the others will be CPU named, OR is that the wrong way (i.e. making AVX2 into john.exe, and then falling back to lower CPU types) ?   I have never used fallback before.

**Comment by jfoug** [comment]
I am having problems getting an XOP build done on my AVX2 system.  I try this, and it appears to make XOP, but the exe does not work:

CPPFLAGS="-mno-AVX2 -mxop" ./configure ......

**Comment by magnumripper** [comment]
Of course, that is a cross compile. XOP is AMD-specific and not included in AVX2.

**Comment by jfoug** [comment]
But I have copied to my xop, and same problem laptop and same problem  Crashes on first format DES.

**Comment by jfoug** [comment]
I did not expect it to run on my intel box.  I am just trying to make several builds to package.

If I build on the laptop, I can get SSE2 and XOP.  If I build on the desktop, I can get SSE2 and AVX2 (or AVX), but I can not get AVX2 to work building on the xop box, or XOP working building on the AVX2.  I am pretty sure there must be something still wrong.  Could it be some '-native' stuff causing trouble?

**Comment by jfoug** [comment]
Got it (I think), running tests now.

CPPFLAGS="-mno-avx2 -mxop" ./configure --disable-opencl --disable-native-march --disable-native-tests

That one works.  When I try to run it on my intel, I get proper 'Sorry, XOP required for this build'   Also, the tests output 'yes' where they should, and XOP is the build type.  the configure does not 'list' yes for cross-compile, but I think things are working.

Magnum, how do the CPU fall back executable naming convention work?  I would like to setup this binary 'pack' in that manner.

**Comment by magnumripper** [comment]
```
$ git grep "define ..._FALLBACK"
john.c:#define OMP_FALLBACK_PATHNAME JOHN_SYSTEMWIDE_EXEC "/" OMP_FALLBACK_BINARY
john.c:#define CPU_FALLBACK_PATHNAME JOHN_SYSTEMWIDE_EXEC "/" CPU_FALLBACK_BINARY
params.h:#define OMP_FALLBACK                   0
params.h:#define OMP_FALLBACK_BINARY            "john-non-omp"
x86-64.h:#define CPU_FALLBACK                   0
x86-64.h:#define CPU_FALLBACK_BINARY            "john-non-avx"
x86-64.h:#define CPU_FALLBACK_BINARY_DEFAULT
x86-64.h:#define CPU_FALLBACK_BINARY            "john-non-xop"
x86-mmx.h:#define CPU_FALLBACK                  0
x86-mmx.h:#define CPU_FALLBACK_BINARY           "john-non-mmx"
x86-sse.h:#define CPU_FALLBACK                  0
x86-sse.h:#define CPU_FALLBACK_BINARY           "john-non-sse"
x86-sse.h:#define CPU_FALLBACK_BINARY_DEFAULT
x86-sse.h:#define CPU_FALLBACK_BINARY           "john-non-avx"
x86-sse.h:#define CPU_FALLBACK_BINARY           "john-non-xop"
```

**Comment by kholia** [comment]
@jfoug https://45.33.2.252:2443/JtR-win64-base.zip use an improper SSL certificate.

Additionally, I see "Your IP is banned, no further requests will be processed from this IP (XYZ)" when accessing that URL (after accepting  the SSL warnings show by the browser).

**Comment by kholia** [comment]
Also, our MinGW builds crash due to bugs in john itself! Specifically, they crash on format's "done" function, when the "done" function calls the "free" function.

**Comment by jfoug** [comment]
I  wonder if mingw is having problems with our aligned allocation

**Comment by vapor99** [comment]
Compiled Windows builds would be very nice because I find it impossible to compile an OPEN CL enabled build myself and cannot find a binary anywhere with OpenCL enabled.  I have tried everything and just cannot do it, and I really dont want to use oclHashcat

**Comment by jfoug** [comment]
I would think it will be very unlikely if an pre-built openCL will be made available.   @kholia what do you think?

First off, I am NOT about to provide support for pre-built exe files.  It seems to me, that OpenCL is great for better speed, BUT (HUGE BUT HERE), they are a support nightmare.

**Comment by magnumripper** [comment]
> they are a support nightmare.

Why? As long as you have built a binary with OpenCL support, I see no reason it shouldn't be just fine. It will require something like OpenCL.dll, right? Not much difference than a binary that requires some winpcap.dll or whatever.

**Comment by magnumripper** [comment]
OTOH binaries in general (OpenCL or not) are a support nightmare, maybe that's what you meant? I agree!

**Comment by jfoug** [comment]
That was more what I meant.  If 'ALL' that is required would be a DLL, then I agree. BUT for openCL, there IS more.  The card has to be supported, and the just being there is that enough for things to 'run' properly?  Would that depend upon the version of catalyst, or GPU architecture they have?  If all those have really simple answers then we probably 'could' do a 64 bit GPU build, and include that also.  I am just not going to waste my time getting it running on every users box, and if it ends up simply being a support sink hole, it would get dropped so fast ppl will wonder if it was ever there ;)

**Comment by magnumripper** [comment]
FWIW we don't support any particular cards (oclHashcat does, and I hate that fact). We basically support **any** OpenCL device. On Linux and Mac, you can upgrade or downgrade your driver and/or replace your card to some totally different one, and still use the same JtR binary. On Windows, it *should* be like that too, but who knows - they are notorious for doing the Wrong Thing[tm] most of the times.

But regardless of OpenCL, I personally don't want to get involved in any kind of binary distribution.

**Comment by jfoug** [comment]
I would not mind having a robot build of 'some' cygwin binaries, under the absolute rule of ```Hey, if they work for you, great, if not then figure the shit out yourself```  (hmm, I should copyleft that for a license agreement, lol).   I can live with a distro plan like that, lol.

**Comment by vapor99** [comment]
@jfoug I like that moniker.  I used the same compiled OpenCL linux binary on two different boxes with different video cards and it pleasantly worked well.  I'm guessing Windows should be the same but who knows with MS?  Still I'm stuck at just compiling the OpenCL windows binary to begin with.

**Comment by magnumripper** [comment]
I'd rather have someone put how a how-to for building Windows OpenCL. But I certainly can't do it myself, I do not touch Windows - ever. Life is FAR to short to bother with that fecking bastard of a general miserable utter failure of an excuse of an operating system. Ouch, sorry 'bout that, I suffer from PTSD out of that piece of s*** from working professionally with it for tens of years.

**Comment by vapor99** [comment]
I hear you there, trust me.  I was forced to use Windows for about 20 years myself, lost hair over it and was nearly institutionalized over it.  Unfortunately I'm limited to using some clustered Windoze machines as much as I dont want to, and am writing a RESTapi (Python celery) to split up jobs between them.  The beauty part is that they all contain very nice video cards that I feel bad for because they having nothing to do.  lol.  A how-to would be great if anyone has done a Win OpenCL build.  I would be willing to share my async code with everyone once its done.

**Comment by magnumripper** [comment]
LOL, you are a good guy @vapor99 I can tell that. Now if we could just get @jfoug over to the bright side, we're set.

**Comment by jfoug** [comment]
Never!

**Comment by vapor99** [comment]
Thanks @magnumripper I try.  After years of work with my psychiatrist trying to communicate and sessions of screaming "Its blue!  Its blue!  The goddamn thing is blue! (MS screen of death)" like the movie Liar Liar, I snapped out of it; got released out of my padded room and was advised to avoid that environment all together.   My mantra to go forward was to tell myself it is out of my control.  Nice and calmly I avoided it for years, until recently the shaking started to return.  lol.  My goal is to take as least time as possible to get a OpenCL build to run on the Church Of Micro-ology so I dont fall back into the deep abyss of ignorant blue monsters hiding in the back of my mind and get re-admitted to the psyc ward at MS hospital.  You wouldn't want that guys would you?

**Comment by kholia** [comment]
Giving access to folks doesn't seem to be simple. If I am gone for a while, the following steps can be used to update / replace the Docker image which we use in CircleCI.

```
$ cat Dockerfile 
FROM fedora:25
MAINTAINER username

RUN dnf install mingw64-openssl mingw64-openssl-static \
mingw64-gcc mingw64-gcc-c++ mingw64-winpthreads-static \
mingw64-zlib-static mingw64-libgomp binutils git make \
automake gcc gcc-c++ zip findutils mingw64-gmp \
mingw64-wpcap wine -y

RUN dnf install openssl openssl-devel zlib-devel \
gmp-devel libpcap-devel -y

RUN dnf install glibc-headers.i686 glibc.i686 glibc-devel.i686 \
libgcc.i686 openssl-devel.i686 gmp-devel.i686 \
libpcap-devel.i686 -y
```

Put this file inside a directory, and from within the directory run,

```
$ sudo docker build -t "username/fedora:25" .
```

Get an account on https://hub.docker.com/ site.

Push this newly built image to Docker Hub.

```
$ sudo docker login

$ sudo docker push username/fedora:25
```

Change `circle.yml` to point to `username/fedora:25` instead of `dhiru/fedora:25`. Change `username` and `25` suitably.

Now that this is documented, I am going to close the issue.
