### ISSUE TITLE
Intrinsics: Improve reversing of steps for SHA-2

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1758]
I think last three steps can be reversed with no pain at all for all SHA-2 formats.

**Comment by jfoug** [comment]
But the only reason to do this, is on raw (or single iteration) formats.  Making this change on something with 1000 (or 100000) iterations is pointless, and the side effects due to a .00001% improvement are not worth it.  Side effects are things such as my code to find casing failures.  This was not even dreamed about until just a couple days ago. But the extra code, and changes in debuggability certainly are other concerns.  Yes, WHEN it makes a difference, then the side effects are certainly justified. BUT where there is absolutely no noticeable improvements in performance, we should not be doing the reversing  IMHO.  I would think anything past about 2 or 3 crypt iterations is pointless.

But for single limb hashes (raw, simple salted, etc), bring it on.  I was pretty impressed with speed gains on the MD[45] you did.  If sha-2 formats can also gain, then great!

**Comment by claudioandre** [comment]
- I wasn't happy with the results in SHA2 OpenCL.

**Comment by magnumripper** [comment]
> But the only reason to do this, is on raw (or single iteration) formats.

Yes, obviously. Single-iteration formats, salted or not.

> I wasn't happy with the results in SHA2 OpenCL

For SHA-2, just skipping last three steps should be a 4% gain. If you don't see it, that's probably a hint something else can be improved.

**Comment by claudioandre** [comment]
> just skipping last three steps should be a 4% gain

I (kind of) disagree. Disclaimer: I need a computer to get the real numbers, but I hope the main point is clear:
- transfer data from host to device:                            1 ms
- transfer data from __global to __private (registers): 1ms
- call block():                                                               20ms
- transfer results back to host:                                    1 ms

Even is this situation, 4% gain is not possible any more. Ok, using a CPU it is.

**Comment by magnumripper** [comment]
Sure but that is a strange point of view. Any boost is good. Solar's recent work with loading 29M hashes looked silly at times (hey guys I saved 300 ms out of 49 seconds) but in the end he saved a whole lot of seconds.

**Comment by claudioandre** [comment]
I'm not saying it is a bad thing. I'm saying: on a GPU the gain was disappointing.

BTW: the reversing will be back (but not for mask mode where a full comparison is done inside GPU).

**Comment by magnumripper** [comment]
As of 72af172 we reverse seven steps for SHA-256 and we'll soon do the same for SHA-512. As far as I understand we can't do it for SHA-224/384, they'll be stuck at three because of unknown data when reversing.

**Comment by magnumripper** [comment]
Reopening for seven steps of SHA-512

**Comment by magnumripper** [comment]
Implemented in a73a7742 and for MSSQL12 in 409fa047
