### ISSUE TITLE
mask mode: wrong parsing of argument

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#1765]
Use of ?s after bracketed character class seems to fail. The following commands should work the same.

$ john --session=test --mask='?1?1' -1='?s[a-z]' --stdout | wc -l
[...]
3481p 0:00:00:00 100.00% (2015-09-14 01:49) 21756p/s zz
3481

$ john --session=test --mask='?1?1' -1='[a-z]?s' --stdout | wc -l
[...]
676p 0:00:00:00 100.00% (2015-09-14 01:49) 3557p/s z !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~z !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
676

Report on john-dev:
http://openwall.com/lists/john-dev/2015/09/13/24

**Comment by magnumripper** [comment]
I'm leaning towards both are incorrect input (so the bug is we don't choke on it and warn user). They should be `-1='[?sa-z]'` and `-1='[a-z?s]'` - or just `-1='?sa-z'` and `-1='a-z?s'`

For `-1` ... `-9` the argument is *one* list of characters and there are implied brackets around all of it unless already present. So valid arguments are eg. `[a-z]`, `a-z`, `[?l]`, `[?d?l]`, `[a-z?d]` but not `[a-z][0-9]`.

**Comment by magnumripper** [comment]
Hmm I think I see a way to make it valid without sacrifying unambigousness to the parser. I'll have a look.
