### ISSUE TITLE
tag 1.8.0.6-jumbo1 was deleted

### ISSUE THREAD

**Issue by rofl0r** [magnumripper/JohnTheRipper#1802]
my john package for sabotage linux relied on the tag to download it. it is usually considered bad to delete stuff or force-push from official git repos.
why was it done ?

**Comment by magnumripper** [comment]
It was described in #1788. Actually, you made me aware of the problem in #1783: GitHub will list any tag as a "release" which these indeed was not. Latest release is 1.8.0-jumbo-1. So we ditched the intermediate tags.

**Comment by magnumripper** [comment]
Why, or in what way, are you relying on intermediate core tags?

**Comment by rofl0r** [comment]
i used the tag to download from github: https://github.com/sabotage-linux/sabotage/blob/master/pkg/john#L2
the previous official release is very old and iirc didnt compile with libressl (which we use as a replacement for openssl)

**Comment by magnumripper** [comment]
OK. Unfortunately the core tags (that were deleted now) in no way indicated a more stable version than otherwise so you could just as well download the very latest snapshot. I'm sorry for the confusion, though I consider it a bug in GitHub.

Hopefully we'll be able to actually release a 1.8.0-jumbo-2 within a reasonable timeframe.
