### ISSUE TITLE
Dynamic ad-hoc format, escaping.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1830]
This initially works just fine:
```
-form:dynamic='md5($u.$c1.$s.$c1.$p),c1=:
```
It loads and cracks things. But it doesn't recognize its own .pot entries because of the `:` in the constant so --show will not show any cracks.

We need to either bail out with error if constant contains `:` or automagically convert it to `c1=\x3a`.

**Comment by jfoug** [comment]
The convert is on my todo list. I just have not gotten to it.  It needs to be in the 'normalization' phase of dyna-dyna

**Comment by jfoug** [comment]
11f1dd5

There still is much more to do in 'normalization', but this issue IS now addressed.  I only auto escape ':' char in consts.  Nothing in salts.  Salts are not part of the expression, but part of the actual input hashes.  Those will also need escapes, BUT I think that is done already in dyna ($HEX$ logic).
