### ISSUE TITLE
Review uses of ctype macros

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1847]
See #1841.

We should review all uses of ctype macros like `islower()` and verify that they only mean handling a-z / A-Z. Rexgen is probably an exception (it does set a locale and needs UTF-8) but most others can probably be replaced with simple inline code (like `^ 0x20`).

mask.c uses ctype macros for ?W (case-toggled base word in hybrid mode). This should be replaced with something from unicode.c that actually handles our configured encodings (as in --encoding options, NOT the system locales).

**Comment by jfoug** [comment]
Actually, if we 'want' to be only ascii case changing, then we should properly build the 256 byte conversion maps like 'ctype' used to be.

So we would have

extern char _john_to_upper[256], _john_to_lower[256];

#undef tolower
#undef toupper
#define tolower(a) _john_to_lower[(ARCH_INDEX(a)]
#define toupper(a) _john_to_upper[(ARCH_INDEX(a)]

Then simply fill in _john_to_upper[] to be 1 to 1 for every character other than 'a' to 'z' where those are simply 'A' to 'Z', and the reverse direction for _john_to_lower[]

Part of the problem is that these have 'grown' very ugly (such as intrinsics, etc).   It may be better in the long run to simply search for all ctype stuff, and IF we want it to be only ascii, then write 100% our own code, and CHANGE the code in each source/header file to only use our code, then every once in a while audit new code for ctype usage.  This is somewhat what we had to do with free()   We simply switched them all to MEM_FREE() macro, and then every once in a while have to audit to find any free()'s that sneak in.   It usually only kills VC (which may be the only one where free() can not be used any more).

**Comment by magnumripper** [comment]
We do use things like `strcasestr()` a lot - isn't that too ctype dependent? So maybe we should simply allow use of any ctype stuff - but state somewhere that we will never run in anything other than the 'C' locale.

**Comment by jfoug** [comment]
It would make sense to me to simply stay in 'C' locale, and use our own custom stuff for other CP's or character sets.
