### ISSUE TITLE
mask mode with iteration has broken estimated time left

### ISSUE THREAD

**Issue by crioux** [magnumripper/JohnTheRipper#1940]
when you specift --min-length and --max-length with --mask, it iterates over all the lengths. When switching from one length to the next it resets the 'estimated time left' and starts over. The estimated time is not calculated over all the combinations for all lengths, only over the combinations for a particular length.

**Comment by magnumripper** [comment]
This is by design. oclHashcat happens to work the same way but that's not the reason we do it: The reason is it's much easier to implement - and personally I find it more informative. Let's say I start a job with `-mask=?a -min-len=0 -max-len=12` without thinking about how long it will take. After a day at, say, length 8 I start to get impatient but then I can see that the ETA for this length is bearable so I let it continue. When it switches to length 9, it will emit a status line (provided john.conf has `MaskLengthIterStatus = Y`) so I see that something happened. Pressing a key I get the ETA for current length which is, say, a month, so I choose to cancel at that point and use a smaller mask (but starting at length 9 now).
