### ISSUE TITLE
./john --test=0 is not deterministic

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1978]
See https://github.com/magnumripper/JohnTheRipper/issues/1952#issuecomment-169143873

IMHO, a variable number of tests is expected when running --test=SECONDS for any SECPONDS > 0, but not for --test=0.

**Comment by magnumripper** [comment]
IIRC, -test=0 actually means 100 ms. So it's just as indeterministic as -test=1. I think this comes from john proper.

**Comment by jfoug** [comment]
Nothing can be done.  This is all timer driven.  When we do -test=0 we call setitimer with 0 values (or sig_timer_emu_init for non-OS_TIMER systems).  What happens after that is OS dependent.  The builds with non OS_TIMER probably will only test 1 value, since they have to emulate a timer.  However, even there, they 'may' run for up to 1ms (or possibly 55ms for any Win based system, no, just tested, it is 2 runs, so for non OS_TIMER it is deterministic).

But all in all, this is sys dependent, and is NOT deterministic.

NOTE, it 'could' be made deterministic, by ALWAYS simply bailing out if !benchmark_time.  I think I should spin wait for the wait to end after that.  Let me if if this can be done.   This was actually pretty easy, and I will get it checked in.

**Comment by jfoug** [comment]
2c284ab

**Comment by magnumripper** [comment]
Does a full --test=0 run complete significantly faster now?

**Comment by frank-dittrich** [comment]
Non-GPU build: self test time down from about 30 seconds to about 25 seconds.
The slow formats with many self tests or with a few expensive self tests cannot be made faster by skipping the benchmark. The same is probably true for most GPU formats.

But the faster self test is just a side effect. THe main benefit IMHO is that --test=0 now is deterministic.
