### ISSUE TITLE
Multiple dynamic scripts using same dyna number should warn user.

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1988]
I am not sure how this will be done.  I think the information about duplication is already lost by the time we get to dyna loading.   But I am adding this issue, just in case someone has an idea on how to do this.

**Comment by frank-dittrich** [comment]
I guess it is the same with two List.Rules sections with the same name:

```
$ head -n 6 john-local.conf 
[List.Rules:test1]
A0"test1"

[List.Rules:test1]
Az"test1"

```

```
$ ./john --stdout --wordlist --rules=test1|head
Press 'q' or Ctrl-C to abort, almost any other key for status
123456test1
12345test1
passwordtest1
password1test1
123456789test1
12345678test1
1234567890test1
abc123test1
computertest1
tiggertest1
```

So, the second definition just overwrites the first without any warning.

Now we can label it as a core John (master) bug.

**Comment by jfoug** [comment]
Not sure calling it a 'bug' is right.  This is a 'feature', lol.  It was done this way by design.   For rules, it may make sense to do this.   non-jumbo john does not have -rules=xxx  Only -rules    But for dynamic, it does not make as much since.  Once a number is 'used', redefining it to some other hash would be a big usage problem.

BUT figuring this one out is NOT trivial, unless you read in dynamic.conf (and anything it loads) and parse it out, without using the config code already writing into jtr.

**Comment by frank-dittrich** [comment]
It is the same with parameter sections.
This is the redefinition in my local config. I didn't use `[Local:Markov:Default]` as a section name, that's why the MkvLvl definition is gone now. (My local definition just has Statsfile and MkvMaxLen.) 
```
$ ../run/john --list=parameters:markov:default 
statsfile = $JOHN/stats
mkvmaxlen = 11
```

And --list=listdata:section also shows the last definition:
```
$ ./john --list=list-data:list.rules:test1 
Az"test1"
```

**Comment by frank-dittrich** [comment]
But redefining a rules section also is a big usage problem, say you just restart a session which resumes with the redefinition instead the original section...

**Comment by jfoug** [comment]
This is just the 'common' code within configure.  it will overwrite already existing lines when reading.

**Comment by frank-dittrich** [comment]
My examples weren't about overwriting existing lines (That would be `[Local:---]` sections, but about overwriting complete sections.

**Comment by jfoug** [comment]
I would be very hesitant about changing the current behavior.  BUT I think a warning being written each time it happens (section) might be good to do.  At least the user would be made aware that an already defined section has been replaced, and that there may be a problem with the setup to investigate.

**Comment by frank-dittrich** [comment]
Yes sure, I'd also suggest to just print a warning (with --verbosity >= 3)

**Comment by magnumripper** [comment]
Would we want that warning when using john-local.conf? I think not. Perhaps at verbosity > 3.

**Comment by frank-dittrich** [comment]
I never change john.conf, just john[.-]local.conf, so a warning with verbosity > 3 would be almost useless.

BTW, it could be we have a memleak for multiple sections with the same name /just looking at cfg_add_section now, didn't tst with ASan, and may be I had one beer too much.

**Comment by jfoug** [comment]
There will be no 'shown' memleak.  Almost all conf code uses mem_alloc_tiny

**Comment by jfoug** [comment]
The above commit has this logic.

If a non-merged section starting with 'list.' is replaced and we are not processing john-local.conf, then we always emit a warning.   If we need to fine tune the output, it should be easy, but at least this is the location WHERE this warning logic needs to be placed.

**Comment by magnumripper** [comment]
Sounds good

**Comment by jfoug** [comment]
So this is 'good enough'.  If so, this bug is closed.  I know the 2 of you bounced some additional ideas around. This change does not go that far.  It simply always 'warns', UNTIL you get to john-local.conf.  I did not warn there, but possibly we should even warn there ?...?

**Comment by frank-dittrich** [comment]
Why only warn when the redefinition is outside john-local.conf?
I can't see why you would want to redefine a john.conf section in john-local.conf. Any examples where this would be desired?

**Comment by frank-dittrich** [comment]
Furthermore, without seeing a valid reason to redefine a john.conf section, I would always assume a duplicate session name and thus a redefinition of a previous session is never intended.
May be a user isn't aware that section names are not case sensitive, and uses

```
[List.Rules:append_a]
<*$a


[List.Rules:append_A]
<*$A
```

That's why I'd prefer to always warn about the redefinition, even with default verbosity and even if the redefinition occurs in a local config file.

**Comment by frank-dittrich** [comment]
Furthermore, without seeing a valid reason to redefine a john.conf section, I would always assume a duplicate session name and thus a redefinition of a previous session is never intended.
May be a user isn't aware that section names are not case sensitive, and uses

```
[List.Rules:append_a]
<*$a


[List.Rules:append_A]
<*$A
```

That's why I'd prefer to always warn about the redefinition, even with default verbosity and even if the redefinition occurs in a local config file.
