### ISSUE TITLE
linux-x86-64 legacy build fails

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#2014]
```
$ make -s -f Makefile.legacy linux-x86-64
ar: creating aes.a
x86-64.o: In function `DES_bs_crypt':
(.text+0x80): multiple definition of `DES_bs_crypt'
DES_bs_b.o:DES_bs_b.c:(.text+0x1666): first defined here
x86-64.o: In function `DES_bs_crypt_25':
(.text+0x1f00): multiple definition of `DES_bs_crypt_25'
DES_bs_b.o:DES_bs_b.c:(.text+0xbbd): first defined here
x86-64.o: In function `DES_bs_crypt_LM':
(.text+0x4200): multiple definition of `DES_bs_crypt_LM'
DES_bs_b.o:DES_bs_b.c:(.text+0x21a1): first defined here
x86-64.o: In function `DES_bs_crypt_plain':
(.text+0x6500): multiple definition of `DES_bs_crypt_plain'
DES_bs_b.o:DES_bs_b.c:(.text+0x3081): first defined here
john.o: In function `CPU_detect_or_fallback':
john.c:(.text+0x2980): undefined reference to `CPU_detect'
collect2: error: ld returned 1 exit status
Makefile.legacy:1866: recipe for target '../run/john' failed
make[1]: *** [../run/john] Error 1
Makefile.legacy:466: recipe for target 'linux-x86-64' failed
make: *** [linux-x86-64] Error 2
```

A `linux-x86-64-avx` legacy build succeeds.

**Comment by frank-dittrich** [comment]
PEBKAC, sorry

**Comment by Strong1983** [comment]
Hello There,

I'm a gentoo linux user and I'm trying to update my laptop... My portage repository is trying to compile johntheripper-1.8.0 but ti fails with the following error:

x86_64-pc-linux-gnu-gcc DES_fmt.o DES_std.o DES_bs.o DES_bs_b.o BSDI_fmt.o MD5_fmt.o MD5_std.o BF_fmt.o BF_std.o AFS_fmt.o LM_fmt.o trip_fmt.o dummy.o batch.o bench.o charset.o common.o compiler.o config.o cracker.o crc32.o external.o formats.o getopt.o idle.o inc.o john.o list.o loader.o logger.o math.o memory.o misc.o options.o params.o path.o recovery.o rpp.o rules.o signals.o single.o status.o tty.o wordlist.o unshadow.o unafs.o unique.o c3_fmt.o x86-64.o -Wl,-O1 -Wl,--as-needed -fopenmp -lcrypt -o ../run/john
john.o: In function `main':
john.c:(.text.startup+0x89): undefined reference to `CPU_detect'
john.c:(.text.startup+0xc0): undefined reference to `CPU_detect'
john.c:(.text.startup+0xed): undefined reference to `CPU_detect'
john.c:(.text.startup+0x533): undefined reference to `CPU_detect'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:835: ../run/john] Error 1
make[1]: Leaving directory '/var/tmp/portage/app-crypt/johntheripper-1.8.0/work/john-1.8.0/src'
make: *** [Makefile:184: linux-x86-64] Error 2
make: Leaving directory '/var/tmp/portage/app-crypt/johntheripper-1.8.0/work/john-1.8.0/src'

I hope that you can give me some clue about the problem... thanks a lot!

Best regards.

**Comment by solardiz** [comment]
Hi @Strong1983. As far as I can tell, the issue you report is with Gentoo packaging, not with JtR. The version of JtR you build there is not jumbo. The version of JtR you build there is out of date. That version did build properly for Linux x86_64 when we tested it. Thus, you may want to bring this issue up with Gentoo, so that they update the package to a current version (1.9.0 core, 1.9.0-jumbo-1, or a current in-development jumbo) and make it work on their current distro. (Assuming that your package is the latest they have. I didn't check. If you didn't build their latest, then you need to update first.)

Also, you added your question to an issue that is only tangentially related. This is almost an issue hijack. Frank's issue was about legacy build in jumbo, yours is about legacy build in core when invoked from Gentoo packaging, likely with overridden CFLAGS and such (which can well cause issues). Quite a different issue from what was originally reported. And the original was found to be a non-issue, too - I guess Frank forgot a `make clean` after a different build.

Finally, our use of GitHub is to track development issues with jumbo, not to provide user support. For user support, we have the john-users mailing list.

**Comment by Strong1983** [comment]
thanks a lot for your reply... it really was very useful!

:D
