### ISSUE TITLE
GPU Mask mode is not working with --encoding

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#2024]
When encoding is in use, GPU mask mode needs to handle characters that are more than 1 byte long. It seems to be unable to do so. 

Command:
--mask:?A?A?A?A --internal-codepage=ISO-8859-1

printf inside set_key() - GPU mask mode **on**. I see only ASCII. 
Non ASCII will be 'produced' inside GPU (how could prepare_key() from nt_opencl help in this case?)
V: 4 #35a 
V: 4 #NSe 
[no more]

printf inside set_key() - GPU mask mode **off**:
V: 5 æNSe
V: 5 §35a 
V: 5 £35a 
V: 4 ;35a 
[...]

Cracks

```
§35a             (?)
æNSe             (?)
```

---

Thinking about bytes, an example could be:

| set_key() | Len | One Case | Obs |
| --- | --- | --- | --- |
| #35a | 4 | a35a |  |
| #35a | 5 | æ35a | Should be ##35a? |

JtR HEAD GPU mask mode only produces: #35a len: 4

Important:
1. after set_key(), key length won't change.
2. workaround: disable GPU mask mode -> export _GPU_MASK_CAND=0 (some formats)

---

If set_key() produces an ASCII string like this #35a:
1. how could I possibly know on GPU that some encoding magic will take place.
2. and, that it will happen for some generated keys. E.g.: no -> 135a -  yes -> æ35a

**Comment by magnumripper** [comment]
If the mask contains non-ASCII you'll be forced to use an internal (or target) codepage and this works like a champ with the formats I've worked with. So nt-opencl and lm-opencl are fine.

I guess you see this problem in a non-Unicode (as in non-UTF16) format. Perhaps any such format with GPU-side mask mode also needs GPU-side encoding stuff just like nt-opencl et. al.

**Comment by claudioandre** [comment]
Ok, I can see a post processing on GPU. It even changes len (when necessary). 

I will try to find your posts about --encoding in JtR lists. At this moment, I would say I'm confused. 
****

../run/john ~/crame_me -form=raw-sha512 -mask:?A?A?A?A (CPU format)

Note to self. What happens:
* if I set FMT_UTF8 or FMT_UNICODE format flag
* if I don't set it.
* --encoding=ISO-8859-1 is different from --internal-encoding=ISO-8859-1
* --internal-encoding=ISO-8859-1 is equal to --internal-codepage=ISO-8859-1
* --encoding=ISO-8859-1 produces guesses --internal-encoding doesn't. And failed to find all guesses --internal-encoding can get.

**Comment by magnumripper** [comment]
9cecf81ed probably has clues, **but** it's for UTF-16. For a format like raw-sha512 we'd need to end up with UTF-8 after GPU-side conversion. I actually never though of this delicate problem.

**Comment by magnumripper** [comment]
> For a format like raw-sha512 we'd need to end up with UTF-8 after GPU-side conversion.

...and to be more correct, it'd need to end up with whatever **target-encoding** was requested.

**Comment by claudioandre** [comment]
My TODO List:
- [ ] set_key("#35a"). 
  - [ ] I have this inside mask_int_cand.int_cand: [0] 00000061  [N] 000000df  [N+1] 000000f7 

How produce the desired characters, ranging from len=1 to len=3 (CP 720), using 61, df and f7 code/index?

**Comment by magnumripper** [comment]
Thinking loud and maybe stating some obvious:

For any format that internally uses UTF-16 (and thus sets FMT_UNICODE), we can set the target codepage to *whatever we want*, so obviously we set it to the *same as the internal codepage* (less conversion needed). This also means we have an 8-bit (codepage, not multibyte) candidate sent to set_key() and also an 8-bit (codepage) GPU-side mask. Easy enough. The conversions on GPU-side are always 8-bit -> 16-bit (using a fast lookup table) so lengths are no issue. Five octets ---> five 16-bit words. Always. The problem you face is new to us and is due to the fact we're not ending up with UTF-16.

raw-sha512, sha512crypt and most other formats are usually expecting UTF-8 input nowadays but it normally doesn't "matter" codewise - they are simply transparent. They don't handle encodings, they just use whatever is sent to `set_key()` as-is. That means we'd have this as long as we don't use GPU-side mask:
`Mask mode (using internal codepage) ----> enc_to_utf8() ----> set_key(UTF-8)`
(the enc_to_utf8 is handled by core code)

But for GPU-side mask, we'll have to do it like:
`Mask mode (using internal codepage) ----> set_key(codepage)`
and then **on GPU-side** we complete the (still 8-bit codepage) candidate *and only then* convert the completed candidate to UTF-8 if that's our --target-encoding. This is fairly trivial but it might eat some performance.

**Comment by claudioandre-br** [comment]
Bug closed because it:

* **Duplicate** - This issue has been reported in another bug, or shares the same root cause as another bug.

Duplicate of #1629
