### ISSUE TITLE
Disable all formats that fails on a super/well/whatever

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2045]
I found a bad optimization inside the new NVIDIA driver. So, I tried a ```--test=0 --format=opencl``` to see how bad it could be. Then, I noticed that at least one format is broken forcing JtR to fail and quit.

* To keep test easy, why not disable any un-maintained format? 
* The format is still there and can be used [1].
* If people start to complain, at least, maintainers would have motivation to do something.

[1] Even when disabled, you can use them as long as you spell them out with the --format option.

**Comment by frank-dittrich** [comment]
Which format failed? May be there's already an open issue for it.

You can add a section `[Local:Disabled:Formats]` to your john-local.conf file and disable formats which currently don't work. (I suggest you also add a comment).

```
[Local:Disabled:Formats]
# comment...
md5crypt-opencl = Y
```

You can still test this format with --format=md5crypt-opencl, but without --format or with --format=gpu etc. it will be skipped.

--list=format-all-details will show if a format is disabled.

**Comment by jfoug** [comment]
This can be done today.

What we need to do is to construct a file in the ./run directory on whatever box you want to disable a format.

That file is ./run/john-local.conf

In that file (it should NEVER be checked into git tree, and is in ./gitignore to keep it from happening), put this:

```
[Local:Disabled:Formats]
bcrypt-opencl = Y
```

Change the bcrypt-opencl to whatever format is failing.  You can have as many lines as you want of disabled formats.  I do this on my sparc system at times (more in the past, before I built my sparc CI), since there are formats that crash.

**Comment by claudioandre** [comment]
I am aware of it. In fact, I opened john.conf to check what I can find
there and copied [1] from there.

* My point is: it is not difficult to find bad formats. IMHO, they have to
be disabled.
* Why JtR team do not disable any format in john.conf?

If this is by design, the issue is a PEBCAK.

**Comment by jfoug** [comment]
It is 100% by design to not place any formats into john.conf.   John.conf is 'owned' by JtR development.  It gets overwritten each time any git pull is done.  That is why it should be placed into a file that is 100% owned by the user, local to their machine.  That is john-local.conf

The section is in john.conf MOSTLY as a template of what needs to be done locally, IF you want to disable something.   NOTE ,that most settings, IF they are going to be hand edited, should be done so within john-local.conf, and NOT in john.con.  If done in john.conf, I will assure you, sooner or later they will get wiped out.

**Comment by claudioandre** [comment]
Ok.

**Comment by frank-dittrich** [comment]
I  opened three new issues for failing opencl formats on super:
https://github.com/magnumripper/JohnTheRipper/issues/2048 (lotus5-opencl)
https://github.com/magnumripper/JohnTheRipper/issues/2049 (Raw-SHA512-ng-opencl)
https://github.com/magnumripper/JohnTheRipper/issues/2050 (sha512crypt-opencl)

sha512crypt-opencl doesn't need to be disabled for --test, because it just fails self test, and john continues testing other formats.

**Comment by magnumripper** [comment]
I kind of agree with @claudioandre that formats that doesn't work well and is not fixed promptly should be disabled. On the other hand it often is due to some particular bad driver and in that case disabling the formats for everyone is not that good an idea.
