### ISSUE TITLE
get_power_of_two doesnt exist on MSVC

### ISSUE THREAD

**Issue by crioux** [magnumripper/JohnTheRipper#2091]
The default implementation of "get_power_of_two" doesn't exist in MSVC and things fail to compile. Also, the #define that is in common-opencl.h would suffice if it were moved to common.h so it could be used everywhere, except for the two cases where it is used strangely in src/opencl_rawsha512_ng_fmt_plug.c  and src/opencl_rawsha256_fmt_plug.c:

```
elements = (get_power_of_two(elements)) + 1;
```
can be changed to 
```
get_power_of_two(elements);
elements++;
```

and
```
		size = (get_power_of_two(memory_available));
```
can be replaced with 
```
{
   size = memory_available;
   get_power_of_two(size);
}
```

**Comment by claudioandre** [comment]
My fault, I'll fix the formats.

**Comment by magnumripper** [comment]
We don't really support building on MSVC as far as I know. I think @jfoug use to build "some" of Jumbo in MSVC for debugging.

**Comment by jfoug** [comment]
I do not do opencl building/debugging in VC (thus my lack of doing too much development of those formats).   So if someone else is doing VC builds of opencl, then they may be wanting certain things which fail compile.  BUT since this is somewhat of a non-supported build, I think it is up to whoever is wanting this to find proper fixes and submit patches to get things working.
