### ISSUE TITLE
Add support for handling "Key Files" in KeePass 2

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2104]
See https://github.com/magnumripper/JohnTheRipper/commit/2c46a0d10fec3997841c4fff3a217c5b1ce87559 too.

**Comment by Fist0urs** [comment]
Hi @kholia 

I'll take a look at that, as I said, but first I'd like to take a look to Keepass 1 keyfile handling within john and things seem a bit confusing:

looking at keepass2john, you print_hex the content of keyfile but in keepass_fmt_plug.c there are some strange things done:

seems like there is an additional "hexlen" and that's wrong

https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/keepass_fmt_plug.c#L268

Also the possibilities are only 32 or 64 bytes while parsing the provided input whereas keepass2john offers the possibility to inline bigger data.

I don't quite understand looking at the code what does john expect with provided keyfile: content of the keyfile in hexadecimal? Content unhexadecimal? (because generating a keyfile, I get a file containing a 64bytes hexadecimal string).

Could you give me some precisions please?

Thx!

**Comment by kholia** [comment]
Hi!

I have some travelling plans this week. So give me two weeks (at max) to reply back. Thanks for taking a look at this :+1:

**Comment by Fist0urs** [comment]
No problem, have a good time ;)

**Comment by Fist0urs** [comment]
Ok to close this issue
