### ISSUE TITLE
WinZIP performance optimization broken

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2141]
https://hashcat.net/forum/thread-5451.html

We had the optmization in place but 528e6bc disabled it:
http://www.openwall.com/lists/john-dev/2016/05/13/1

**Comment by jfoug** [comment]
I will re-evaluate this, BUT I certainly do not want to lose the exact manner of zip.  I have not looked into this speed up at all, but bet it is not much, UNLESS the .zip file is very large.

I think I was the one that found the optimization years ago (skipping to the end since these use ECB mode).  I think it can easily be re-added, and only in cmp-exact do we do the FULL check.

I will add this to my todo list, when I have time.  I am so buried right now, that I am not sure when I will get to it.

**Comment by solardiz** [comment]
Jim -

On Tue, May 24, 2016 at 09:27:47AM -0700, jfoug wrote:
> I will re-evaluate this, BUT I certainly do not want to lose the exact manner of zip.  I have not looked into this speed up at all, but bet it is not much, UNLESS the .zip file is very large.

It sounds like you misunderstand what this is about.  It is not about
speeding up AES - it is about speeding up PBKDF2.  So the speedup is
significant, and not just for large files.

**Comment by jfoug** [comment]
I will reevaluate when I have time.   I lost a pbkdf2 speedup to get the exact testing???  I am a bit surprised there, since I always look for the 1/2 work of pbkdf2.

But it should still be easy to put the optimization back, and then only perform the full testing within cmp_all, so that we do not fall back to the NON_EXACT behavior we had from the first POC version.

**Comment by jfoug** [comment]
I know the speedup you are referring to (the seeking within pbkdf2). So that should be easy to put back in.

**Comment by magnumripper** [comment]
Fixed, and implemented in OpenCL too. It's actually a 2x..4x boost, never less than 2x.
