### ISSUE TITLE
Crack Sparsebundle

### ISSUE THREAD

**Issue by Saurman** [magnumripper/JohnTheRipper#2145]
Sorry for writing here but I've spent 4h trying to figure out how to use ur tool. I have OS X Sparsebundle, password protected and id like to figure out the password. Please advice where to read, what commands to execute, i am not that good with linux stuff and console

**Comment by magnumripper** [comment]
This is not a support forum.

**Comment by solardiz** [comment]
On Sun, May 29, 2016 at 04:05:26PM -0700, magnum wrote:
> This is not a support forum.

+1, but maybe we should explicitly direct people to the john-users mailing list when they (wrongly) open GitHub issues. Saurman, please feel free to join the john-users mailing list and post in there.

Also, maybe we should enhance the documentation. I notice we already have doc/README.Apple_DMG in the tree, but it's very brief (as it should be?) - maybe we could write a longer tutorial, including a specific (fake or otherwise not security sensitive) example, placing it under http://openwall.info/wiki/john/tutorials - any takers?

README.Apple_DMG talks about the dmg2john binary only, but now we also have the dmg2john.py Python script, which may be more appropriate to use when the actual password cracking is to proceed on another machine anyway (e.g., on Linux with GPUs), thus eliminating the need for having a binary build of JtR on the Mac (and thus not needing Xcode, nor a binary JtR download). Maybe README.Apple_DMG should be enhanced to mention this possibility as well.

Finally, I recall that running dmg2john and then JtR on the result was meant to be part of Johnny's functionality to be implemented during last year's GSoC - perhaps we have it in there? If so, that should be part of the tutorial as well.

I think all of this should in fact be brought up on john-users, for much greater visibility than just to the few people reading this GitHub (non-)issue. That way, we would more likely reach someone willing to contribute.

Sparsebundle / dmg file cracking keeps coming up in private e-mail and tweets to me, somehow more often than it does on john-users. We could really use some better documentation focusing on this specific aspect.
