### ISSUE TITLE
./jtrts.pl test for agilekeychain-opencl format fails

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#2240]
On super, with `scl enable devtoolset-3 bash` built with --disable-openmp.

john version shown as `1.8.0.6-jumbo-1-2574-gec1bb74+`, but I don't know where the '+' comes from, since I don't have any local changes. 
```
form=agilekeychain-opencl         guesses: 1200 -show=1200 0:00:00:12 DONE : Expected count(s) (1500)  [!!!FAILED1!!!  ret_val=0]
```

Not sure whether 1200 guesses is to be expected now (so that the test suite needs to be adjusted).

**Comment by jfoug** [comment]
1200 is very likely correct. I will have to see how the input files were made, and the PLAINTEXT_LEN for the cpu and opencl, and see if 1200 is right.

But a lot of these super slow ones were built with only 25 words and the same salt, then those same 25 words were run with a different salt (but same for that group of 25) and then 25 again, over and over again, until 1500 total were done.  So there are 60 groups of 25 (single salts). Since 1500-1200 is divisible by 60, then it is very likely that 5 of the passwords are simply too long for the opencl. 

But what I will do is run my script, and make sure that there are 5 passwords we would not be able to crack with opencl. If that is the case, then 1200 will be added as acceptable to the jtrts.dat file for this format.

**Comment by jfoug** [comment]
Yes, this is exactly what is expected:

 $ ./count_finder.pl 125 64 25
Found 25 of length 125  (required 25 total lines to do)
Found 20 of length 64

**Comment by jfoug** [comment]
79b5b97
