### ISSUE TITLE
./configure erroneously detects AVX2 under VMware Workstation Pro 12

### ISSUE THREAD

**Issue by jeffmcjunkin** [magnumripper/JohnTheRipper#2384]
Using latest -jumbo code (commit 29f04d887b927cdbd3ae33e811e43b6f5a5b17c6) on Ubuntu 16.04.1 inside a VMware Workstation Pro 12 (12.5.2 build-4638234) VM:

```
$ grep flags /proc/cpuinfo
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm epb fsgsbase smep dtherm ida arat pln pts
```

So I wouldn't expect AVX2 to be detected. However...

```
$ ./configure | grep -C 1 -i avx2
checking for XOP... no
checking for AVX2... yes
checking for AVX512F... no
```

After running `make`, the newly-build `john` binary doesn't work:
```
$ run/john
Sorry, AVX2 is required for this build
```

Exporting CPUID_DISABLE as mentioned in https://github.com/magnumripper/JohnTheRipper/issues/2089 does work, but isn't ideal:

```
$ export CPUID_DISABLE=1
$ run/john | head -n 1
John the Ripper 1.8.0-jumbo-1-5468-g29f04d8 OMP [linux-gnu 64-bit AVX2-ac]
```

Requested information:
```
$ git branch
* bleeding-jumbo
$ run/john --list=build-info
Version: 1.8.0-jumbo-1-5468-g29f04d8
Build: linux-gnu 64-bit AVX2-ac OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
$JOHN is run/
Format interface version: 14
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 5.4.0
GNU libc version: 2.23 (loaded: 2.23)
Crypto library: OpenSSL
OpenSSL library version: 01000207f
OpenSSL 1.0.2g  1 Mar 2016
GMP library version: 6.1.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by magnumripper** [comment]
This must be a bug in vmware. Having said that, I wouldn't mind working around it.

**Comment by magnumripper** [comment]
Does the actual host support AVX2 or not?

**Comment by jeffmcjunkin** [comment]
Yes, it does (it's an i7-4702HQ in this case):

```
$ grep flags /proc/cpuinfo  | head -n 1
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
```

**Comment by jfoug** [comment]
Again this is what I consider a shortcoming of the cpuid_detect function INSIDE john.  The configure probes by blindly trying instructions.  Just because some VM's are not properly handling all of the CPUID instructions EXACTLY like the actual iron does not mean that the instructions do not work properly within the VM.

But currently the only way around this problem is using the CPUID_DISABLE.   Virtual box has the same issues.  The binary AVX2 runs fine for me, EXCEPT in john's cpuid_detect function.

**Comment by solardiz** [comment]
Jim, I think it's risky, if not plain wrong, to use AVX2 if it's not reported as present via cpuid.  This is a path to getting false negatives (correct passwords occasionally not cracked), because the guest kernel would not save/restore AVX2 state on context switch (thinking the CPU doesn't even support AVX2).

The correct fix should be for the configure test to match JtR's startup test, and for both to use cpuid rather than probe instructions.

It is unfortunate not to use AVX2 in VMs when this "appears to work", but to do it "properly" we'd have to be doing tricks like what folks did (e.g., in the distributed.net DES cracking effort) back when Solaris ran on 64-bit gear and supported it in the kernel, but had a 32-bit userland and thus didn't save upper halves of 64-bit integer registers on SPARC V9.  That is, detect context switches through some known-to-be-clobbered registers and redo the computations in that case.  This is hackish, complicated, and time-consuming to get right and "fully" test - and then a new version of Linux kernel, or non-Linux indeed, might break the detection.

**Comment by magnumripper** [comment]
I agree with Solar: The tests in john are not the problem - the ones in ./configure are.

**Comment by jfoug** [comment]
Read the Intel dox on cpuid, and they actually talk about this as one of the methods, in fact a good choice when it comes down to some of the complex detection, where there are numerous interdependent instruction set bits, but only part of them would be used within the running process.

I agree that the VM's are not right.  Why they do not support the entire kitchen sink of AVX2 flags I do not know.  But also keep in mind, WE do not use the entire kitchen sink of AVX2 extensions.

**Comment by claudioandre** [comment]
To debug purposes, why not just print what cpuid detects. 

POC:
```
From e8c194343e939c5cd770f5b49ce7c81afbdd1c3a Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Claudio=20Andr=C3=A9?= <claudioandre.br@gmail.com>
Date: Fri, 20 Jan 2017 13:49:15 -0200
Subject: [PATCH] build: use cpuid on configure

---
 src/configure | 54 +++++++++++++++++++++++++++++++++++++++++++++++++++++-
 1 file changed, 53 insertions(+), 1 deletion(-)

diff --git a/src/configure b/src/configure
index 76a00a6..d33bfab 100755
--- a/src/configure
+++ b/src/configure
@@ -8268,9 +8268,61 @@ else
 
     #include <emmintrin.h>
         #include <stdio.h>
+        #include <cpuid.h>
         extern void exit(int);
-        int main(){__m128i t;*((long long*)&t)=1;t=_mm_slli_si128(t,7);if((*(unsigned*)&t)==88)printf(".");exit(0);}
 
+        #ifndef bit_SSE4_1
+        #define bit_SSE4_1 0
+        #endif
+
+        #ifndef bit_AVX2
+        #define bit_AVX2 0
+        #endif
+
+        #ifndef bit_AVX512F
+        #define bit_AVX512F 0
+        #endif
+
+        #ifndef bit_AVX512BW
+        #define bit_AVX512BW 0
+        #endif
+
+	void cpu_id(void)
+	{
+		unsigned int eax, ebx, ecx, edx;
+
+		printf("CPUID: ");
+
+		if (!__get_cpuid(1, &eax, &ebx, &ecx, &edx))
+			printf("CPUID(1) Error");
+
+	        if (edx & bit_SSE2)
+			printf("SSE2 ");
+
+	        if (ecx & bit_SSSE3)
+			printf("SSSE3 ");
+
+	        if (ecx & bit_SSE4_1)
+			printf("SSE4.1 ");
+
+	        if (ecx & bit_AVX)
+			printf("AVX ");
+
+		if (!__get_cpuid(7, &eax, &ebx, &ecx, &edx))
+			printf("CPUID(7) Error");
+
+	        if (ebx & bit_AVX2)
+			printf("AVX2 ");
+
+	        if (ebx & bit_AVX512F)
+			printf("AVX512F ");
+
+	        if (ebx & bit_AVX512BW)
+			printf("AVX512BW ");
+		printf(". ");
+	}
+
+        int main(){__m128i t;*((long long*)&t)=1;cpu_id();t=_mm_slli_si128(t,7);if((*(unsigned*)&t)==88)printf(".");exit(0);}
 
 _ACEOF
 if ac_fn_c_try_run "$LINENO"; then :
```

[1] you can put your assembly here if you want.
[2] works on gcc and clang.
[3] VC has something similar.

**Comment by jeffmcjunkin** [comment]
Further information I discovered this morning -- VMware hardware version 10 (released with VMware Workstation 10) doesn't have AVX2, but VMware hardware versions 11 and 12 do have the AVX2 extensions:

virtualhw.version = "11"

```
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm epb fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid xsaveopt dtherm ida arat pln pts
```

virtualhw.version = "12"

```
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm ida arat epb xsaveopt pln pts dtherm fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid

```

**Comment by jeffmcjunkin** [comment]
Even with the above new information, I agree it's safer to probe for reported-as-supported extensions in the `configure` script, rather than trying instructions blindly, if only because it's nearly impossible to be sure something that isn't reported as being supported is 100% working in every possible way `john` could use it.

**Comment by solardiz** [comment]
On Fri, Jan 20, 2017 at 06:40:48AM -0800, jfoug wrote:
> I agree that the VM's are not right.  Why they do not support the entire kitchen sink of AVX2 flags I do not know.  But also keep in mind, WE do not use the entire kitchen sink of AVX2 extensions.  

Wouldn't this simply be the effect of running a version of hypervisor pre-dating the introduction of AVX2?  Those AVX2 instructions are not privileged, so they would appear to "work" if the host kernel enabled AVX, yet cpuid, which the hypervisor may trap, wouldn't report AVX2.

And this got me thinking further: maybe we're actually OK with instruction probing in this specific case, because AVX was already 256-bit for floating point, meaning that if the guest kernel knows AVX, we're OK wrt state saving/restoring on context switches.  So maybe the combination of a cpuid check for AVX (to ensure the guest kernel knows at least AVX) and probing for AVX2 instructions is reliable.

In general, though, we should use cpuid.  The above is more of an exception than the rule.

**Comment by jeffmcjunkin** [comment]
Reading further, the timeline does match up. VMware Workstation 10 was released in September 2013 (https://en.m.wikipedia.org/wiki/VMware_Workstation), and the Haswell architecture (which introduced AVX2) came out from June or so in 2013 (https://en.m.wikipedia.org/wiki/Haswell_(microarchitecture)), depending on the CPU. That's probably too little time for VMware to get the new extensions in the virtual CPU config.

**Comment by jfoug** [comment]
These are not 'pre-date'.  VirtualBox at one time worked with john's internal cpuid code.  It then broke it.  It is likely there are a few things which virtualbox does NOT properly handle, so they shut off certain things.  

BUT these were some of the ancillary things, which john 'probes' for, since it documented that multiple instruction sets are actually IN the silicon pressed, EVEN if john does not use those instructions (there are 3 or 4 instruction sets probed to 'state' that AVX2 is enabled, but we only use the AVX2 itself at this time).

IIRC, we chatted about this same situation, about 3-4 years ago when I was doing the ./configure script, and adding the probing detects.  I think there was simply 1 instruction 'set' (i..e cpuid bit) that was missing on the virtualbox stuff.  Likely they found some problem in some regression testing, so simply turned that CPUID bit off, to claim that feature was not there.  I bet it worked 'most' of the time, and only certain usages of it were even bad, but to CYA, they 'disabled' it in cpuid.   AFAIK, they have not turned some of them back on yet.  I just run cygwin shells on the VM's and simply set the environment var to ignore the CPUID check in john, and on my systems, things are working just fine.

NOTE, just because the version of virtual box I use DOES work sensibly, doe NOT mean other VM's would also work.  It would have to be up the end user to test that the build WAS working.  Yes, ./configure probes, seeing if the AVX2 instructions run without throwing ill-instruction exceptions (i.e. get passed through to the silicon), and that is working fine for my builds (and I have seen).  But is that always going to be the case in every VM?  I can't say.
