### ISSUE TITLE
can't start john, got munmpa_chunk() error

### ISSUE THREAD

**Issue by caledot** [magnumripper/JohnTheRipper#2445]
### Steps to reproduce

My environment: Ubuntu 14.04 in windows 10
What I'm doing: just finished the 'make' phase and runned the test command

### System configuration
I've just installed Jumbo but i cannot start John in any way. Everytime i try to start it, even to get report of my build info i got the following error:

![image](https://cloud.githubusercontent.com/assets/25247851/23791797/b0231a86-0584-11e7-8370-83c9ec445bfa.png)

How can I solve this?

Thanks in advance

**Comment by kholia** [comment]
You are supposed to answer the questions asked in the issue template. Edit your post and give all the details on how to trigger this bug.

**Comment by caledot** [comment]
Post edited

**Comment by kholia** [comment]
How did you install JtR jumbo on Windows? Where did you get it from?

Use the latest native Windows build of JtR jumbo, which you can download from http://daily-builds.appspot.com/latest URL.

**Comment by kholia** [comment]
You should be using "john-users" mailing list to get support. This is not a place to get support.

**Comment by frank-dittrich** [comment]
@kholia 

I don't think that @caledot wants to use a windows build.

> My environment: Ubuntu 14.04 in windows 10

@caledot 
I think you will need to provide some more information, either on the john-users mailing list or here.
(I'll reopen this issue just in case you can provide that information. If it turns out there's no JtR bug, Dhiru will probably close it again.
But with the additional information we might tell you whether there's a MicroSoft bug causing this problem or whether the john-users mailing list is the right place to answer your questions.)

Does this mean you are running ubuntu 14.04 inside a Windows VM?

Or are you trying to use native ubuntu programs from the Windows 10 cmd.exe?
http://blog.dustinkirkland.com/2016/03/ubuntu-on-windows.html

> What I'm doing: just finished the 'make' phase and runned the test command
```
$ ../run/john --test=0
```
from your "screenshot"
https://cloud.githubusercontent.com/assets/25247851/23791797/b0231a86-0584-11e7-8370-83c9ec445bfa.png
looks you are running an ELF binary built for ubuntu.

If so, the problem could also some MicroSoft bug.

What is the output of
```
../run/john --list=build-info
```
Or, if that doesn't work, the first 3 lines of output of 
```
../run/john
```

Can you provide a back trace of that core, to get some more info?
That should be the output after the
```
Aborted (core dumped)
```
line.

You should be able to copy the text from that output instead of uploading an image.

**Comment by kholia** [comment]
I don't see any good reason to use "non-platform-native" builds unless you are doing development and testing work. 

Using such lightly-tested combinations (i.e. running an unknown Linux build on Ubuntu-on-Windows environment) for end user is not recommended, especially when we have well tested builds available. Even if we want to support such stuff, use the mailing list to get support.

https://github.com/magnumripper/JohnTheRipper/ clearly says "Nor is it the place to report bugs you see in any version of Jumbo other than the LATEST, from HERE.".

Due to all these reasons, I am closing this issue again.

**Comment by claudioandre** [comment]
I found no bugs on JtR HEAD
* The WSL (windows subsystem for linux) build and run of JtR is working.

**Comment by frank-dittrich** [comment]
@claudioandre How is the performance, compared to a native windows build, or compared to a native linux build running on the same hardware?

**Comment by claudioandre** [comment]
>How is the performance [...] compared to a native linux build running on the same hardware?

* Fair enough. I compared a few formats at https://claudioandre.github.io/outros/winux_en.htm

****
Sooner or later, it will be easy to automate the production of a JtR WSL build that:
* handle all formats;
* has fork;
* handle file locking;
* etc.

**Comment by kholia** [comment]
The user mentioned a browser tab crash (in a duplicate issue) which occurred when the user was editing this issue. Are RAM problems behind this crash? Or is some WSL bug more likely behind this crash? Just wondering.

**Comment by claudioandre** [comment]
>  Or is some WSL bug more likely to cause this crash?

It is possible. I was using the stable and updated WSL (Windows Build 14393, I guess). 
* He/she could be using an outdated or beta (insider preview) build.
