### ISSUE TITLE
Incorrect MaxChar for NTLM

### ISSUE THREAD

**Issue by mubix** [magnumripper/JohnTheRipper#2529]
Attempting to crack an NTLM hash with a known password fails to crack:
```
Password: Onceuponatimeinepisode5season2  
NTLM Hash: CB4D7AFFB476FD9B39A1447C1A66B564 
```

Checking the format details it says it supports up to 81 characters:
```
root@crackingbox:/opt/jtr/run# ./john --list=format-details --format=nt
NT      81      24      24      0002000f        43      MD4 256/256 AVX2 8x3                    -1      16      0               0       b7e4b9022cd45f275334bbdb83bb5be5
```

John.log
```
0:00:00:00 - Hash type: NT (lengths up to 81)
```

Nothing to really show since it doesn't crack it successfully. But I'm also having the same issue with Kerberos TGS hashes with known passwords.

### System configuration
```
Version: 1.8.0-jumbo-1-5397-gde7d7cd
Build: linux-gnu 64-bit AVX2-ac OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 4.9.2
GNU libc version: 2.19 (loaded: 2.19)
Crypto library: OpenSSL
OpenSSL library version: 01000114f
OpenSSL 1.0.1t  3 May 2016
GMP library version: 6.0.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by magnumripper** [comment]
This is not really a bug, it's more of a quirk. The NT formats have a max length of 27 characters. That is true even with Unicode characters, since the format uses UTF-16 internally.

The problem is that in order to get 27 Unicode characters we might need (up to) 81 bytes of UTF-8 input, so in case you run `--input-encoding=utf8` (which is the default now), that is what we set. Most of legacy john code can't tell the difference between bytes and characters, and the result is what you see. We're pretty much stuck with this problem.

The only way to solve all Unicode issues with all crackers (including but not limited to JtR and hashcat) would be (I think) to re-write them from scratch, and treating all strings as UTF-32 internally, almost everywhere.

**Comment by solardiz** [comment]
On Thu, May 04, 2017 at 02:07:34PM -0700, magnum wrote:
> The problem is that in order to get 27 Unicode characters we might need (up to) 81 bytes of UTF-8 input, so in case you run `--input-encoding=utf8` (which is the default now), that is what we set. Most of legacy john code can't tell the difference between bytes and characters, and the result is what you see. We're pretty much stuck with this problem.

Since the character encodings support is jumbo-specific, maybe jumbo could deduce the range of max supported plaintext lengths (in this case, 27 to 81 input bytes, depending on what characters those are) and report it accordingly (that is, as a range) in john.log and in format details?  This doesn't sounds like it'd require major core changes.  The current reporting is confusing and feels very much like a bug (which is why I asked Rob to report it in here).

**Comment by magnumripper** [comment]
> Since the character encodings support is jumbo-specific, maybe jumbo could deduce the range of max supported plaintext lengths (in this case, 27 to 81 input bytes, depending on what characters those are) and report it accordingly (that is, as a range) in john.log and in format details?

That should be doable. Re-opening for implementing that.

**Comment by magnumripper** [comment]
https://github.com/magnumripper/JohnTheRipper/commit/45131f1dba1c09b287a8e2519cb9f041eee1d977#commitcomment-22134658

**Comment by frank-dittrich** [comment]
See also the ASCII length 0 mentioned in my second comment to your commit (for dynamic formats):

```
$ ./john --list=format-all-details|egrep -n "( to 0 |dynamic)"|grep -A 2 " to 0 "
4300:Max. password length                 41 [worst case UTF-8] to 0 [ASCII]
4312: A $dynamic$ format                  yes
4313: A dynamic sized salt                no
--
4733:Max. password length                 36 [worst case UTF-8] to 0 [ASCII]
4745: A $dynamic$ format                  yes
4746: A dynamic sized salt                no
--
5570:Max. password length                 36 [worst case UTF-8] to 0 [ASCII]
5582: A $dynamic$ format                  yes
5583: A dynamic sized salt                no
--
5972:Max. password length                 36 [worst case UTF-8] to 0 [ASCII]
5984: A $dynamic$ format                  yes
5985: A dynamic sized salt                no
--
6665:Max. password length                 26 [worst case UTF-8] to 0 [ASCII]
6677: A $dynamic$ format                  yes
6678: A dynamic sized salt                no
--
7385:Max. password length                 36 [worst case UTF-8] to 0 [ASCII]
7397: A $dynamic$ format                  yes
7398: A dynamic sized salt                no
--
7787:Max. password length                 28 [worst case UTF-8] to 0 [ASCII]
7799: A $dynamic$ format                  yes
7800: A dynamic sized salt                no
--
8163:Max. password length                 36 [worst case UTF-8] to 0 [ASCII]
8175: A $dynamic$ format                  yes
8176: A dynamic sized salt                no
8191:Max. password length                 36 [worst case UTF-8] to 0 [ASCII]
8203: A $dynamic$ format                  yes
8204: A dynamic sized salt                no
8219:Max. password length                 5 [worst case UTF-8] to 0 [ASCII]
8231: A $dynamic$ format                  yes
8232: A dynamic sized salt                no
```

**Comment by magnumripper** [comment]
31b19c2 adds a tweak for LM formats. This should be fine (enough) now.

**Comment by mubix** [comment]
Thanks @magnumripper - this is awesome :)  👍
