### ISSUE TITLE
No password hashes loaded 

### ISSUE THREAD

**Issue by saru95** [magnumripper/JohnTheRipper#2656]
I trying to run JtR on an MD5 hash and repeatedly getting this error.

```
No password hashes loaded (see FAQ)
```

I've tried a simple command such as `./john hashes.txt` let alone using a wordlist.

I've also run `sudo ./unshadow /etc/passwd /etc/master.passwd > mypasswd` as I'm on an OSX machine. I still get the same error.

My `hashes.txt` looks like 

```
3ac7f40aaf2929374315d0f3de69553
39fa99caedf2585347dd2dc28e7a486
```

**Comment by solardiz** [comment]
GitHub issues aren't a user support forum - they're for reporting issues in the software itself. For user support, there's the john-users mailing list.

That said, in your particular case the non-loading of raw MD5 hashes is most likely caused by you using the "official" JtR instead of "jumbo". Raw MD5 support is jumbo-specific. (The official JtR, as well as JtR Pro, focus on operating system passwords, and raw MD5 isn't used by operating systems - rather, it is commonly (mis)used by web apps.)

The "sudo ./unshadow ..." command is not applicable to OS X, which stores password hashes differently. Instead, you'd use jumbo's lion2john.pl or lion2john-alt.pl scripts, or Pro's xpwdump script. The exact procedure varies between OS X versions.

If you have any further questions, please join the john-users mailing list and ask in there. Please make sure to use a specific message Subject that would reflect both your question and the likely discussion that will follow. Thanks.
