### ISSUE TITLE
Default verbosity hides important messages

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#2717]
I was surprised to find that jumbo no longer prints by default many messages that core does. Those messages include most warnings printed by `john_omp_show_info()`, which are critically important for extracting reasonable performance out of JtR. They also include messages logged (not even printed to the terminal!) by `inc.c`, `single.c`, `wordlist.c`, although I understand that messages about wordlist rules could get noisy and waste lots of disk space, especially with some custom rulesets. In code, these are checks like `options.verbosity >= VERB_LEGACY`.

I think we should make jumbo's messages printed by default to be the same as core's, except possibly for too verbose logging that could waste disk space. In place of such logging, we should log one message explaining that some log messages are suppressed at current verbosity level and can be re-enabled with the `--verbosity` option.

To me, at least the message suppression in `john_omp_show_info()` is a blocker for next release.

**Comment by magnumripper** [comment]
Should be fixed in a2f8cde. I think the actual wordlist problems were limited to the use of --pipe - because then rules are processed over and over again. So now only --pipe will suppress, and only after a threashold of 1000 rules - and a message is logged about it.

Most other mentioned logging was reverted to VERB_DEFAULT or even to be unaffected by verbosity.
