### ISSUE TITLE
Inconsistent build on AVX-capable CPU with pre-AVX kernel

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#2764]
Trying to build on an AVX-capable CPU (in this case Ivy Bridge) with a pre-AVX Linux kernel (in this case RHEL5) results in an inconsistent binary not runnable on the system: it prints "Sorry, SSE4.1 is required" and exits. Examining `x86-64.o` reveals it actually checks for AVX. Examining the generated `Makefile` shows:

```
CFLAGS = -DAC_BUILT -march=native -msse4.1 -DJOHN_SSE4_1 $(CFLAGSX)
ASFLAGS = -DAC_BUILT  -DARCH_LITTLE_ENDIAN=1 -march=native -msse4.1 -DJOHN_SSE4_1 -c -fopenmp   -DHAVE_HT
```

Apparently, `-march=native` defines `__AVX__`, but our `-DJOHN_SSE4_1` takes priority in our `arch.h`.

`./configure --disable-native-march` produced a consistent SSE4.1 build usable on the system.

Can/should we somehow improve the situation? If we've detected SSE4.1 and are passing the explicit `-m` option for it, maybe we should not be also passing `-march=native`? Why do we?

**Comment by magnumripper** [comment]
> Apparently, -march=native defines `__AVX__`

So that's a gcc bug. You can't reliably use AVX without kernel support for it, right?

> If we've detected SSE4.1 and are passing the explicit -m option for it, maybe we should not be also passing -march=native? Why do we?

Because (at least in theory), some future CPU feature could make wonders for JtR without us writing any explicit support for it. Without -march-native, it wouldn't be used.

I haven't decided what to do here, if anything. If you don't want -march=native you should tell ./configure so.

**Comment by solardiz** [comment]
> So that's a gcc bug. You can't reliably use AVX without kernel support for it, right?

Yes. This also results in e.g. `php_mt_seed` non-working in a default build on systems like that.

However, we clearly have a JtR jumbo bug here as well: it fails to even correctly refer to what's required - complains SSE4.1 is required and that's why it'll refuse to run, but SSE4.1 is in fact available.

Besides, we should be able to workaround this specific gcc bug by omitting `-march=native` when our own tests detect SSE4.1 and don't detect AVX. Or we could be even more specific and only omit that option when our own tests (to be made more selective) detect that AVX is supported by the CPU but not enabled by the kernel. It's a matter of checking for a combination of bit flags, should be easy.

**Comment by magnumripper** [comment]
> However, we clearly have a JtR jumbo bug here as well: it fails to even correctly refer to what's required - complains SSE4.1 is required and that's why it'll refuse to run, but SSE4.1 is in fact available.

Yes, we should definitely fix that at least. The actual net problem here is we have CPU_NAME as "SSE4.1" but from dry-running arch.h I can't see why that is happening. Line 116 in x86-64.h should set it to "AVX" and everything looks correct to me. I can't see any logic differing to John Proper's arch.h.

**Comment by magnumripper** [comment]
Actually, in x86-sse.h lines 80-88 there are dupe checks in wrong order that could end up in precisely this - it will reset CPU_NAME to "SSE4.1" for anything that was previously set higher (but also has SSE4.1). I will fix that. However, in your case x86-64.h should be used, and I can't see the bug there.

**Comment by solardiz** [comment]
> I can't see why that is happening.

Here's why: we don't (and shouldn't) include `-march=native` in `CFLAGS_MAIN`, which we use to build `john.c`. So it relies solely on the `JOHN_*` defines. However, we do enable the `-m` options when building the assembly files, so we end up inconsistent with the CPU detection code in those. Maybe this applies to John Proper too, but I haven't seen this issue arise there.

I think we should make our definitions of `JOHN_*` consistent with what the rest of the program is built with. And this probably implies stopping to use `-march=native` since in general we can't reliably infer what it detected.

**Comment by magnumripper** [comment]
Ah yes, got it. So a workaround for ensuring a CPU_NAME consistent with actually built cpuid tests could be to define a global variable cpu_name in some other file (eg. misc.c or (less trivial for me) in the very assembly files) and dereference it in john.c instead of using CPU_NAME.

I don't quite like the idea of dropping `-march=native` completely. I know it doesn't always guarantee the ultimately fastest build, but sometimes it really rocks. Then again, we could make it non-default, as in change --disable-native-march to --enable-native-march (and still do the above). Does that sound like a plan to you?

**Comment by magnumripper** [comment]
We could also refuse the combination of `-march=native` and CPU fallback, to stop distros form making poor decisions.

**Comment by magnumripper** [comment]
@solardiz @jfoug unfortunately I'm back at writing asm although I don't quite master it. I seem to miss some (supposedly) tiny detail. Here's what I basically did:

x86-64.S
```c
.text

#ifdef UNDERSCORES
#define CPU_req_name _CPU_req_name
#endif

.globl CPU_req_name
CPU_req_name:
       .asciz CPU_NAME
```
My intention was to make a global variable `CPU_req_name` that contains the string set in `CPU_NAME` at the time x86-64.o was built. And some dilettant use of `nm` and `objdump` indicate it turned out OK.

It also links fine, but it segfaults when I try to dereference it - the data seems to reside in memory I'm not allowed to read. Here's what I did in C:

listconf.c
```c
#if CPU_REQ
       extern char *CPU_req_name;

       printf("CPU req tests: %s\n", CPU_req_name);
#endif
```
Running it in gdb confirms that CPU_req_name points to an address but I'm not allowed to read it.

I've used up all my google-fu to no avail. I tried putting that assembly definition in other sections but nothing seem to help.

**Comment by solardiz** [comment]
magnum, your asm creates an array of characters followed by a NUL, but your C expects a pointer. That's the problem. You may do:

    extern char CPU_req_name[];

**Comment by magnumripper** [comment]
Oh, right. Very obvious in hindsight... Thanks!
