### ISSUE TITLE
JtR too restrictive when verifying encoded UTF-16 files

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2812]
Since 0ce265dcffff41864143e3bc48de539b4c62649f, JtR is refusing to load a 8bit wordlist. Well, at least all tools I used detected the wordlist as: ascii/unknown, unknown-8bit or iso8859-1.

To see the issue in action (tested on *well*), just
```
./jtrts.pl -noprelims -type MSSql
```

**Comment by magnumripper** [comment]
Not sure how @jfoug ended up with the crazy idea to hash a UTF-16 BOM and even depend on it, but this is a TS issue and not a JtR one (unless you show me a real-world case where this is a problem *).

I dropped the stupid lines from the dictionaries but now we end up with some formats "failing" due to only cracking 1499 out of 1500. This is just stupid, I don't have time to fix it right now. But again, it's a TS issue.

*) If you do find such case, we could drop the check when using `--encoding=raw` but that's about as far as I'm willing to go.

**Comment by magnumripper** [comment]
OK, after some research I changed my mind. I will probably need to revert to only do this check when input encoding is UTF-8. Perhaps still checking the very first line for other codepages though.

BTW the rationale for checking for BOM's on *all* lines is that user may have concatenated several files, where one or some of them were UTF-16 by mistake. I've seen it happen, I've heard it happen.

**Comment by bill-e-ghote** [comment]
Thanks for reverting this. 'twas puking on crackstation.txt, even.

**Comment by magnumripper** [comment]
@bill-e-ghote well, it should... I had a look now - crackstation.txt contains UTF-16 garbage which is precisely what we wanted to detect because all such data is 100% unusable for any format and any crack mode.

That wordlist is by far the very lowest quality I've ever seen. The size of it is a good hint.

Nonetheless, I now relaxed things even further - we now just warn instead of bailing out. That's only for UTF-16 in wordlists though - we still refuse to read any input file containing a UTF-16 BOM.

**Comment by androidacy-user** [comment]
Why the decision to completely not support utf-16? I have a zip file in utf-16 format that's encrypted, on Linux

Sorry to bump a super old issue but googling took me here

**Comment by solardiz** [comment]
On Sat, May 30, 2020 at 06:36:28PM -0700, Alexia wrote:
> I have a zip file I'm utf-16 format that's encrypted

What do you mean by this, and what makes you think that's what you have?

**Comment by androidacy-user** [comment]
> On Sat, May 30, 2020 at 06:36:28PM -0700, Alexia wrote: I have a zip file I'm utf-16 format that's encrypted
> What do you mean by this, and what makes you think that's what you have?

Jtr bails out saying something about having a utf-16 BOM

**Comment by solardiz** [comment]
On Sun, May 31, 2020 at 06:05:37AM -0700, Alexia wrote:
> Jtr bails out saying something about having a utf-16 BOM

This almost always means that you're invoking it incorrectly, _not_ that you need UTF-16 support.

**Comment by ghost** [comment]
> This almost always means that you're invoking it incorrectly, _not_ that you need UTF-16 support.

@linuxandria, please post the command line you are using. 

We need to be sure you are running the `zip2john filename.zip` and NOT _john ZIPFILE_

**Comment by androidacy-user** [comment]
> > This almost always means that you're invoking it incorrectly, _not_ that you need UTF-16 support.
> 
> @linuxandria, please post the command line you are using. 
> 
> We need to be sure you are running the `zip2john filename.zip` and NOT _john ZIPFILE_

Oof lol I was doing that
Had to cd into source/run to even do that bc make install didn't do its thing but that's a different issue
