### ISSUE TITLE
Reuse JtR runtime CPU detection code from configure script

### ISSUE THREAD

**Issue by Florianwall** [magnumripper/JohnTheRipper#2881]
Can anyone help me? installing works just fine, but i cant execute any of the programs like zip2john etc.. always tells me that AVX2 is required for this build. I don't know how to fix this. I am currently running Kali linux on a virtual machine. Couldn't find any similar bugs.

**Comment by solardiz** [comment]
This isn't a user support forum. Helping one particular person isn't the intent of GitHub issues, and thus not a priority when handling of issues reported in here. We have the john-users mailing list for that.

It is known that VMs sometimes incompletely support or proxy host's support for SIMD instruction sets, resulting in inconsistencies like this. A workaround might be to configure with `./configure --disable-native-tests`, although this is likely excessive (will also disable plain AVX, etc., resulting in a greater than necessary performance hit).

That said, thank you for your problem report. What we might be able to do to work around this in JtR jumbo for everyone (which is finally on-topic for a GitHub issue) is to make its configure script's and its runtime CPU detection checks more consistent (ideally, invoke the same code), so that either both will detect e.g. AVX2 or both won't.

We could also make `--disable-native-march` the default, since gcc's CPU detection is also different from ours and is also sometimes wrong in VMs, but per previous discussions @magnumripper does not want to do this (and it makes sense to me as this is how we currently make use of instructions such as MOVBE where available).

**Comment by magnumripper** [comment]
@Florianwall when you say "installing" do you mean building Jumbo from (GitHub) source, or installing some Kali packet?

**Comment by claudioandre** [comment]
https://github.com/claudioandre/JohnTheRipper/commit/e727e7a82de6e592f10723b260afca6847cb31d3

CI is still checking it. But:
* It is working on well (AVX2);
* It is working on Travis VMs (some AVX and some AVX2).

I have no idea what will happen on VC.

**Comment by claudioandre** [comment]
It is not hard to Ctrl+c and Ctrl+v when a change is needed.

**Comment by solardiz** [comment]
Thanks, Claudio. I commented on register clobbering, but more importantly I dislike us introducing (and then maintaining) an inline asm revision of the code. It's certainly not what I meant... although maybe it can help us for now, as a temporary hack.

I'd prefer that we build the same `.S` file from `configure` and later from `make`, and call the exact same `CPU_detect()` function. This might mean also building the actual crypto code found in the same source files, or alternatively we could split out the CPU detection into separate files.

Also, the issue might not be limited to detection of AVX2. Probably it also applies to detection of AVX where the guest OS kernel is not yet AVX-aware, but the host's is (gcc's `-march=native` also fails at this test, though - at least as of gcc 4.6.x).

Ideally, we'd reuse JtR's runtime CPU detection code in all cases where such code is available, and without duplicating/revising that code.

**Comment by jfoug** [comment]
I still am not sold on the CPUID code found INSIDE john.  I have run on VMs and when the instruction set is there, it builds, BUT johns CPUID gets overly anal about some obsure features not implemented.  Every time this happens, if someone simply sets the env var:  CPUID_DISABLE, the format build and all formats run like a champ.

This seems to happen in the AVX2.  The internal code checks for numerous features and if any are no present, then the AVX2 code is not allowed and john abends.

I really think instead of neutering the instruction checks within configure, I think better commenting about using the CPUID_DISABLE environmental flag (especially when running on VMs) might be better.  yes, there may come a day where the configure script builds a specific instruction set that is NOT able to run. But up to now, this has not been the case, ever.  The opposite has been the rule.  code john-proper telling the user this build will not run, when it actually does run.

**Comment by claudioandre** [comment]
It is possible. That said, i bet magnum won't be a happy man.

https://github.com/claudioandre/JohnTheRipper/commit/80e7cb36e4279cda84d12c9b93e54063bf0a806b#diff-a0b12bf816963ad0e0590c06d5bc763c

**Comment by solardiz** [comment]
Note that the AVX2 detection (nor use) isn't yet in "john-proper", although I should probably add them to there soon. The way magnum implemented the AVX2 detection, it also checks for lots of related things that gcc might use with `-march=native` on such a machine. Indeed, if gcc does not actually use them for a given format, that format would run fine despite of them not being present... or they might be mostly present but just not detected in a certain type of VM.

And yes, we should probably document CPUID_DISABLE better. I didn't even recall it when writing my first comment on this issue.

**Comment by solardiz** [comment]
FWIW, I like Claudio's new https://github.com/claudioandre/JohnTheRipper/commit/80e7cb36e4279cda84d12c9b93e54063bf0a806b#diff-a0b12bf816963ad0e0590c06d5bc763c (referenced above). I think we should use that approach.

To address what Jim is saying, we might also want to add a configure option to bypass the compile-time SIMD checks and to force a specific SIMD instruction set - which is needed for producing distro packages anyway.

**Comment by jfoug** [comment]
> configure option to bypass the compile-time SIMD checks and to force a specific SIMD instruction set

Fully agree here!  We currently have a way to skip all those checks, but we do not have a way to SPECIFY use AVX (or AVX2, AVX512, etc) instruction set.  I think it would be nice to allow a simple config param to force the build to utilize a specific CPU flavor.  Would this be needed for cross compiling also??  I am not familiar with the what/why of cross compiling.

Note, I am pretty sure that CPUID_DISABLE is only avail within jumbo.  It was the initial work around to keep the john-proper CPUID from bailing out when the build actually should work.

I thought core already had AVX2 support (8x limbs), and AVX512 (16x limbs).  It certainly speeds things up for little cost, well at least the way jumbo does the SIMD_COEF_32/64 and the intrisics header file.  I do not know much about how flexible the asm source is for core's x86 code. I would hope it was as easy as it has been made in jumbo to use wider SIMD processors.

**Comment by solardiz** [comment]
> we do not have a way to SPECIFY use AVX (or AVX2, AVX512, etc) instruction set.

This may be worked as part of #2862. Yes, also needed for cross-compiling.

Indeed, CPUID_DISABLE is jumbo specific. john-proper doesn't detect any SIMD instruction sets during build - instead, you specify one explicitly with a make target (that's what we have in `Makefile.legacy` in jumbo now). It doesn't have AVX2 and AVX-512 yet (I should add them), but it has AVX and MIC (very similar to AVX-512 at source code level) and NEON and AltiVec.

**Comment by jfoug** [comment]
@Florianwall   I should have replied directly to this earlier.

Set CPUID_DISABLE=1 as an environmental variable prior to executing john (or any of the ancillary programs which are simply a soft link to john).  That env var allows john to run fine and to skip doing it's internal CPUID checking code prior to execution.

**Comment by magnumripper** [comment]
> The way magnum implemented the AVX2 detection, it also checks for lots of related things that gcc might use with -march=native on such a machine.

As far as I understand, it's what a compiler might use with a mere -mavx2.

> BUT johns CPUID gets overly anal about some obsure features not implemented

With all due respect, that's bullshit. We have discussed this before and nothing changed. Just because you didn't see it yet doesn't mean it won't break. **We test exactly what Intel says we have to test, nothing more, nothing less.**  If we said -mavx2 (or -march=native) the compiler MIGHT emit anything we test for. That is true even if *you* never saw it happen.

**Comment by solardiz** [comment]
> As far as I understand, it's what a compiler might use with a mere -mavx2.

magnum, I think you're wrong. Here's an example of gcc refusing to use BMI1 even when explicitly asked to in the source code, when invoked merely with `-mavx2`, and agreeing to use it when invoked with `-mbmi`:

```
[solar@super ~]$ cat bmi.c 
int f(int a, int b)
{
	return __builtin_ia32_bextr_u32(a, b);
}
[solar@super ~]$ gcc -c bmi.c -mavx2
bmi.c: In function 'f':
bmi.c:3:9: warning: implicit declaration of function '__builtin_ia32_bextr_u32' [-Wimplicit-function-declaration]
  return __builtin_ia32_bextr_u32(a, b);
         ^~~~~~~~~~~~~~~~~~~~~~~~
[solar@super ~]$ gcc -c bmi.c -mbmi 
[solar@super ~]$ gcc --version
gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)
```

When we check for AVX2, we also check for BMI1, BMI2, MOVBE, FMA3. We could similarly test if gcc would be willing to use those, and I guess it wouldn't be, implying it wouldn't use them on its own with a mere `-mavx2` as well.

OTOH, when we use `-march=native`, we do have to check for those things since gcc might in fact enable them. But then future gcc might enable even more things, which we aren't even aware of and are not checking for.

**Comment by magnumripper** [comment]
I stand corrected, although I wonder if icc works the same. I followed this: https://software.intel.com/sites/default/files/article/405250/how-to-detect-new-instruction-support-in-the-4th-generation-intel-core-processor-family.pdf (or some similar doc from Intel).

So ultimately we really need to drop `-march=native` altogether, or at least have it as non-default.

**Comment by magnumripper** [comment]
#2966 should make an end to this for good!
