### ISSUE TITLE
7z format's misuse of "%u" on a negative number

### ISSUE THREAD

**Issue by seekaddo** [magnumripper/JohnTheRipper#2998]
In the file [src/7z_fmt_plug.c](https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/7z_fmt_plug.c#L327) `get_salt` uses `atou` (the unsigned form) for conversion, which will result in an undefined behaviour when used with a negative number. kholia added ` a test vector with negative CRC value in 7z format ` but it still didn't fail on self-test.
 @solardiz suggested that we stop using `isdec*` in `valid()`. I think we can use `isdec*` in the valid method (since all negatives will fail in isdecu and isdec) and change the `atou` function in 7z to avoid this undefined behaviour.

I think we can we can use `intmax_t` in the atou function to support signed and unsigned values. We can't use `ssize_t` since is not guaranteed to be bigger than int on all platforms.

**Comment by seekaddo** [comment]
I have something like this in mind. adding little changes to `atou` function. Something like this

```
intmax_t val;
sscanf("4294967295","%li",&val);
```

**Comment by solardiz** [comment]
My suggestion to stop using `isdec*()` in there was when we were going to limit `isdec*()` to 9 9's. We've since decided not to, so this suggestion no longer applies.

Changing `atou()` to accept negative numbers would be very confusing. We should specifically change the 7z format not to use `atou()` when the number is negative (the already-validated string starts with a '-'). We could even use `atoi()` in that case, but we'd need to convert to the corresponding unsigned value afterwards. Alternatively, we could skip the '-' and proceed with `atou()` on the digits portion of the string, but then adjust the resulting value (can be done with purely unsigned 32-bit arithmetic).

**Comment by seekaddo** [comment]
> We've since decided not to, so this suggestion no longer applies.

Yea, you are right.

> Changing atou() to accept negative numbers would be very confusing. 

What I meant was in the 7z where this was used. Changing it to every other function too will be weird. Sorry for the misunderstanding.
