### ISSUE TITLE
pkzip format should emit a #warning when built without libz

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3033]
We should add a build #warning just like for eg. stribog w/o SSE4.1, suggesting to install libz and re-configure/re-build.

**Comment by kholia** [comment]
@seekaddo This is something you may be interested in :-)

**Comment by solardiz** [comment]
I support magnum's suggestion, but I think it's also desirable to emit warnings about incomplete functionality when it would actually have mattered at runtime. Can we have zip2john and john emit a warning when they're run on a file or "hash" that would be supported by a more complete build?

**Comment by seekaddo** [comment]
@kholia thanks for the hints. I will take a look.

**Comment by magnumripper** [comment]
@solardiz that might be a good idea! That would be a separate issue though.

**Comment by jfoug** [comment]
@solardiz a runtime warning would be a nice thing to have (to cut down on some PEBCAK issues being reported). The problem with it, is we would need stripped down formats to do this. At a minimum, the format would need a valid, that would detect a valid pkzip hash, and then report that the hash is not supported in this build.  yes, very doable (and would 'live' in the #else block of the HAVE_ZLIB (along with the compile time message).  But now, we would have a john that states it can handle pkzip format, BUT which really can not.  Are we sure we want to go there??

As for the OP on this thread, yes, this trivial compile time addition should be added.

**Comment by solardiz** [comment]
> we would have a john that states it can handle pkzip format, BUT which really can not. Are we sure we want to go there??

No, we shouldn't go that far. But we may have a john that can partially handle pkzip format, lists this format among its available ones, but when run on an unsupported flavor of the "hash" that would be supported by another build, prints a warning from within valid() before it returning 0.

**Comment by magnumripper** [comment]
So what do we have here? We have valid() that can return 0 (hash not recognized) or 1 (hash supported) or even *n*>1 (hash supported and *n* splits possible IIRC by heart).

What would we do with a non-supported yet recognized valid()? Return a negative?

**Comment by magnumripper** [comment]
OK, mid-air conflict. `prints a warning from within valid() before it returning 0.` is easy.

**Comment by jfoug** [comment]
But (like stribog), can the current pkzip format do anything at all, without that libz library?  that is my point.  Isn't the entire format wrapped in a HAVE_LIBZ define?  I am sure that is the way it is today, because I was just getting ready to check in a patch that fixes this issue.

That was why I asked the question. without zlib, we have no pkzip format at all. BUT should we build a dummy format to inform the user at runtime that a better build would work??  IMHO, no.

**Comment by jfoug** [comment]
If the pkzip format was partially supported, then yes, emit of a warning 1 time within valid is one way.  there are some formats where we do have partial support (gpg, 7z, etc).  I do not think pkzip falls into that situation at all (but I could be wrong).

**Comment by magnumripper** [comment]
I think what solar meant is we would have some kind of dummy pkzip format that only has valid() (really only that) - and would emit a descriptive message before returning 0.

**Comment by solardiz** [comment]
Actually, I thought pkzip could be built with partial support.

Now that I re-read the other issue that prompted magnum to open this one, it looks like the problem is different: it is weird when zip2john works, but john from the same build tree doesn't accept zip2john's output. OTOH, I can see how zip2john can be useful even in such situations - to enable cracking on another machine that does have libz. So it'd be wrong to disable building of zip2john in such cases. It would also probably be wrong for zip2john to emit a warning about john lacking support, unless it's the same binary like it was before (with symlink), so it knows for sure what its john supports or not.

**Comment by jfoug** [comment]
I am pretty sure zip2john is a symlink.

**Comment by solardiz** [comment]
> I am pretty sure zip2john is a symlink.

Oh. So while it remains a symlink, we can have it print a warning to stderr (in addition to doing its job and printing the "hash" to stdout) if built without libz.

**Comment by magnumripper** [comment]
> it is weird when zip2john works, but john from the same build tree doesn't accept zip2john's output

There's yet another parameter: zip2john builds hashes for zip as well as pkzip formats.
