### ISSUE TITLE
zip2john: command not found

### ISSUE THREAD

**Issue by fahad-the-dev** [magnumripper/JohnTheRipper#3266]
I installed the JohnTheRipper.
But in my terminal zip2john is still unknown command

**Comment by claudioandre** [comment]
Although this issue is worded as a bug report, not as a question, I'm afraid you're mistaken [1].

We assume you are genuinely thinking you are reporting a real bug to help the project. That said, please:

- read `INSTALL` and `INSTALL-UBUNTU` located in the sub-directory named `doc`;
- confirm you are using the updated bleeding-jumbo source code (not a numbered release, as this GitHub issue tracker is for issues still present in our latest code, not only in the releases we had made earlier);
- ensure that you ran a `./configure && make -s clean && make -sj8`;
- try to make your point clearer;
- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message Subject when you post).
***
* this is not a support forum.
* zip2john is a symbolic link.
* installed JohnTheRipper? I guess you mean you built it.
