### ISSUE TITLE
Add the option to test the speed of the hash on the CPU core 1-8

### ISSUE THREAD

**Issue by torerobo** [magnumripper/JohnTheRipper#3363]
I wanted to test the speed of the hash on the CPU on one core and on two cores. But the option --fork = ... does not work

```
└──╼ $john --test --format=RAR5 --fork=1 
Invalid options combination or duplicate option: "--test"
```
```
└──╼ $john --test --format=RAR5 --fork=2 
Invalid options combination or duplicate option: "--test"
```

**Comment by claudioandre-br** [comment]
That said

> to test the speed of the hash on the CPU on one core and on two cores.

You can use OpenMP:
```
$ OMP_NUM_THREADS=1 john --test --format=RAR5
Benchmarking: RAR5 [PBKDF2-SHA256 128/128 SSE2 4x]... DONE
Speed for cost 1 (iteration count) of 32768
Raw:	0.7 c/s real, 1.4 c/s virtual
```

```
$ OMP_NUM_THREADS=2 john --test --format=RAR5
Will run 2 OpenMP threads
Benchmarking: RAR5 [PBKDF2-SHA256 128/128 SSE2 4x]... (2xOMP) DONE
Speed for cost 1 (iteration count) of 32768
Raw:	2.2 c/s real, 1.3 c/s virtual
```

**Comment by claudioandre-br** [comment]
Although you have made a valid request, I doubt it will be implemented. IMO: it sounds artificial.
1. you can use `--fork` in a "fake" cracking session (to check the speed);
2. you can use OpenMP.

****
Although this issue is worded as a bug report, not as a question, I'm afraid you're mistaken.

We assume you are genuinely thinking you are reporting a real bug to help the project. That said, please:

- try to make your point clearer;
- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message Subject when you post).
