### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by torerobo** [magnumripper/JohnTheRipper#3397]
Hey.
Tell me how to ask my question here? Http: //www.openwall.com/lists/john-users/ (I can not find a form to fill in the question)

Question: tell me how to get John to work in the increment mode of the figure?
Example john hash --incremental = Digits (I need John to increment the numbers 0,1,2 ... 00,01,02 ...)

**Comment by claudioandre-br** [comment]
Send a message to the mailing list
****
Although this issue is worded as a bug report, not as a question, I'm afraid you're mistaken.

We assume you are genuinely thinking you are reporting a real bug to help the project. That said, please:

- read `INSTALL` and `INSTALL-UBUNTU` located in the sub-directory named `doc`;
- confirm you are using the updated bleeding-jumbo source code (not a numbered release, as this GitHub issue tracker is for issues still present in our latest code, not only in the releases we had made earlier);
- ensure that you ran a `./configure && make -s clean && make -sj8`;
- try to make your point clearer;
- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message Subject when you post).

**Comment by magnumripper** [comment]
http://lmgtfy.com/?q=mailing+list

**Comment by AlekseyCherepanov** [comment]
A better link about mailing lists would be this: https://en.wikipedia.org/wiki/Electronic_mailing_list#Discussion_list

I.e. there is no web-form to submit message, you need to use email to send messages. http://www.openwall.com/lists/john-users/ is one of web-archive interfaces for this mailing list. But archives give read-only access.

The easiest way is to subscribe to the mailing list. IIRC you'll get a help message from the mailing list manager software (ezmlm) after subscription. There you'll find the "To" address for your messages (don't use `-admin` variant, use plain `john-users@lists...` ).

Formally you are not required to be subscribed to send messages onto the mailing list. But it would be convenient for you to be subscribed, because it allows you to respond to the list. (john-users mailing list has tradition to avoid CC to sender in replies, so you will not get a direct reply most probably. So being not subscribed, you would not get the email with reply, but you would be able to see it through the web-archive. Actually gmane could give the email to you, but that's another story...)

Also you might find helpful the following materials about proper formatting of replies on mailing lists:
http://www.complang.tuwien.ac.at/anton/mail-news-errors.html
http://www.netmeister.org/news/learn2quote.html

**Comment by solardiz** [comment]
I've just added "Confused about mailing lists and their use? Read about mailing lists on Wikipedia and check out these guidelines on proper formatting of your messages." (including two hyperlinks in there) to our mailing list archive page footers.

**Comment by torerobo** [comment]
> Лучшая ссылка на списки рассылки была бы такой: https://en.wikipedia.org/wiki/Electronic_mailing_list#Discussion_list
> 
> Т.е. нет веб-формы для отправки сообщения, вам нужно использовать электронную почту для отправки сообщений. http://www.openwall.com/lists/john-users/ является одним из интерфейсов веб-архива для этого списка рассылки. Но архивы предоставляют доступ только для чтения.
> 
> Самый простой способ - подписаться на рассылку. После подписки IIRC вы получите справочное сообщение из программного обеспечения менеджера списка рассылки (ezmlm). Там вы найдете адрес «Кому» для ваших сообщений (не используйте `-admin`вариант, используйте обычный `john-users@lists...`).
> 
> Формально вы не обязаны подписываться на рассылку сообщений в список рассылки. Но вам было бы удобно подписаться, потому что это позволяет вам отвечать на список. (В списке рассылки john-users существует традиция избегать отправлять CC-сообщения отправителю в ответах, поэтому вы, скорее всего, не получите прямой ответ. Поэтому, если вы не подписаны, вы не получите письмо с ответом, но вы сможете просмотреть его через веб-архив. На самом деле Gmane может дать вам электронное письмо, но это другая история ...)
> 
> Также вам могут быть полезны следующие материалы о правильном форматировании ответов в списках рассылки: 
> [http://www.complang.tuwien.ac.at/anton/mail-news-errors.html ](http://www.complang.tuwien.ac.at/anton/mail-news-errors.html)
> [http://www.netmeister.org/ новости / learn2quote.html](http://www.netmeister.org/news/learn2quote.html)

Greetings Alexey!  I need your help in this matter.  I subscribed to the mailing list.  I received a reference guide.  I can not understand what mail to send your question?  I sent a "test" to all the proposed mail and received a "garbage".
john-users@lists.openwall.com
john-users-faq@lists.openwall.com
john-users-get.123_145@lists.openwall.com
john-users-index.123_456@lists.openwall.com

no letter left here
https://www.openwall.com/lists/john-users/

Can you write me a mail "where should I send my question on JtR functionality"?  telegram Andolini123

**Comment by AlekseyCherepanov** [comment]
@torerobo `john-users@lists.openwall.com` is the correct address. Your(?) email with subject `test1` was caught by moderation (as of it was your first email). The email was not delivered to all subscribers as meaningless. Please write real email and send to the address.

**Comment by torerobo** [comment]
@AlekseyCherepanov 
Right!  "test1" is my letter.  You wrote

> Please write real email and send to the address.

(Did I understand the translation correctly?) In order to receive technical support via JtR, I have to send my question to john-users@lists.openwall.com, but I must send it from the mail I signed up with?  And in case of approval of moderation, only then my question will appear here https://www.openwall.com/lists/john-users/

**Comment by magnumripper** [comment]
> but I must send it from the mail I signed up with?

Not really, but you need to send a meaningful message, not a test mail. No-one on the list members are interested in seeing your test mails. The same applies here BTW, you are close to being banned from here.

**Comment by AlekseyCherepanov** [comment]
Sorry! I did mistake: I used "email" incorrectly, I meant "letter" actually. Fixed: please write real letter and send to the address.

You may send to `john-users` mailing list from any email address. But it would be more convenient to use the same email address used for subscription. (When there is a discussion, it is easier to reply into the discussion's thread this way.)

> And in case of approval of moderation, only then my question will appear here https://www.openwall.com/lists/john-users/

Yes, your letter will appear on the web archive after moderation.

**Comment by torerobo** [comment]
> > но я должен отправить его с почты, на которую я подписался?
> 
> Не совсем, но вам нужно отправить значимое сообщение, а не тестовое письмо. Никто из участников списка не заинтересован в просмотре ваших тестовых писем. То же самое относится и здесь, кстати, вы близки к тому, чтобы быть забаненным отсюда.

Ok.  Before I go out from here I went out / (bante).  I’ll report the latest bug in JtR: wpapcap2john in windows does not extract the hash from .cap (in GNU / Linux, it successfully extracts).  The .cap file is the same.  JtR version 1.9.0-1 (last).

Good luck in developing and searching for volunteers.

**Comment by solardiz** [comment]
@torerobo Thanks for the bug report. Can you please open a new issue for just that one bug, and if possible attach a sample .cap file we could use to reproduce the bug? Also, please describe in that issue how exactly the program "does not extract the hash" - what happens instead. Perhaps include some copy-paste from your Windows command prompt window (text only, no screenshots, please).

**Comment by torerobo** [comment]
> @torerobo Thanks for the bug report. Can you please open a new issue for just that one bug, and if possible attach a sample .cap file we could use to reproduce the bug? Also, please describe in that issue how exactly the program "does not extract the hash" - what happens instead. Perhaps include some copy-paste from your Windows command prompt window (text only, no screenshots, please).

Sorry, false alarm (apparently, like many). The problem in the directory, an example of how it is impossible to extract hashes C:\Users\user-test\Downloads\**ddd ddd**\brad.cap
Success C:\Users\user-test\Downloads\**dddddd**\brad.cap

Quotes escaping a space can not help (my fault).

**Comment by magnumripper** [comment]
Good thing you sorted it out! I didn't really mean to be offensive but I confess I was reading mail before having coffee  o.O
