### ISSUE TITLE
SSLeay Compile Issue

### ISSUE THREAD

**Issue by emwinkler** [magnumripper/JohnTheRipper#3402]
I still get the following compile error even with the latest John.  

Undefined symbols for architecture x86_64:
  "_SSLeay", referenced from:
      _listconf_parse_early in listconf.o
  "_SSLeay_version", referenced from:
      _listconf_parse_early in listconf.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [../run/john] Error 1
make: *** [default] Error 2

Output of openssl version - OpenSSL 1.0.2p  14 Aug 2018

**Comment by emwinkler** [comment]
One thing I noticed is that if I explicitly include /usr/local/lib/libcrypto.a, then John compiles fine.  I am compiling this under MacOS 10.13.6.

**Comment by magnumripper** [comment]
The header files you used when building likely doesn't match the dynamic library loaded when running. Not really our fault!

Having said that though, more people will stumble onto this for sure so I consider dropping the SSLeay stuff altogether. The question is, what will *that* break? @solardiz use to want us to support really old stuff. I haven't found any mention of when the newer calls was added but I'm pretty sure there was a significant gap.

Now we could always add autoconf stuff for this but I'd rather drop that code from `-list=build-info` because I don't consider it important enough.

**Comment by kholia** [comment]
I can't reproduce this problem on macOS 10.13.5 with the same OpenSSL version.

**Comment by magnumripper** [comment]
> Now we could always add autoconf stuff for this

Actually I have realized even that won't help: Even a completely correct build for the "old" version will fail when dynamically linked with the "new" version and vice versa. The OpenSSL genii really blew compatibility here. I have an experimental fix in #3406 just for phun but I think the best we can do is completely drop the run-time version checks.
