### ISSUE TITLE
OpenCL lock file should be removed (or use unique name)

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3482]
On super. The errors are: permission denied and segmentation fault:
```
Node numbers 1-3 of 3 (fork)
Device 2: Tahiti [AMD Radeon HD 7900 Series]
1: Error setting build lock: Permiss?o negada
Device 6: GeForce GTX TITAN X
2: Error setting build lock: Permiss?o negada
Device 7: GeForce GTX TITAN
3: Error setting build lock: Permiss?o negada
Falha de segmentação
```

I can't remove it.
```
$ ls -la /tmp/.JtR_kernel_build_lock
-rw-------. 1 magnum magnum 0 Dez  4 10:37 /tmp/.JtR_kernel_build_lock
```

**Comment by magnumripper** [comment]
I wonder why there was a segfault though. I need to look into that separately.

**Comment by magnumripper** [comment]
BTW I probably need to read up on lock files. I deliberately do not unlink them, because if node 0 gets the lock and node 1 is waiting for it and node 2 didn't even get that far, I figured if node 0 unlinks it before closing, node 2 would create a *new* file and lock **that** one instead (at the same time node 1 has a lock on the **deleted** one). I'm not sure that's what would happen but I kinda think so.

Another problem is that Windoze can't unlink an open file but IIRC it doesn't have proper locks with our code anyway so that may be a moot point.

**Comment by solardiz** [comment]
For the `--fork` case, we can `open` and `unlink` in the master process before `fork`, and then be `fcntl` locking via the shared fd. We can also randomize the filename e.g. by using `mkstemp`. With a fixed filename in `/tmp`, any user can DoS us.

**Comment by solardiz** [comment]
And this is a vulnerability, and is totally unacceptable to keep as-is with a filename in `/tmp`:

```c
        FILE *kludge_file = fopen(KLUDGE_LOCK_FILE, "w");
```

At the very least, we must use `O_EXCL`. Its equivalent to `fopen` is `x`, but this might not be portable enough to rely on it for security. In fact, no reason to use `fopen` when our only uses of the file are then passing `fileno` into `fcntl` or `flock`.

**Comment by solardiz** [comment]
> Perhaps we should set it to mode 666.

No. Mode 666 would only let other users store/exchange data in there without it being attributed to them. It wouldn't let other users unlink the file.

**Comment by magnumripper** [comment]
> No. Mode 666 would only let other users store/exchange data in there without it being attributed to them. It wouldn't let other users unlink the file.

Oh right. Damn, I want this KISS.

> In fact, no reason to use fopen

Are you saying I should use `open(2)`? I'm rusty.

Anyway, I actually thought of locking our already existent log file for the session instead. One at a time. That should work. shouldn't it?

**Comment by magnumripper** [comment]
> Anyway, I actually thought of locking our already existent log file for the session instead. One at a time. That should work. shouldn't it?

Hmm, except that won't meet my initital goal of not doing a global lock. On the other hand, I don't think it's much of a problem. Actually, For systems where even directories like `~/.nv/ComputeCache` is shared, it might actually be a good thing.

**Comment by solardiz** [comment]
> As to locking a log file, what if we're running with `-nolog`'?

And if you meant `.rec` files, then those are already fcntl-locked to prevent inadvertent reuse of the running session name. We can't lock them twice. We could possibly build OpenCL kernels before locking them for the session's duration, but that would be an invasive change and it'd have side-effects.

**Comment by solardiz** [comment]
To summarize my current preference: if do we use a lock file perhaps it should be a new one for this very purpose (not the same as a `.log` or `.rec` file), but perhaps it should be located in JtR home (along with our other runtime data files), not in `/tmp`.

**Comment by magnumripper** [comment]
> Also, can/should this locking perhaps be optional? I think most systems were able to build OpenCL kernels in parallel just fine, and we only received occasional problem reports.

I pushed the locking stuff in hope it would fix #3450 because it did solve major problems with some combos of nvidia and MPI, but it looks like it didn't fix that issue. I should probably keep it but push it back to `#if HAVE_MPI` sooner or later. I'd like it to be in the air for a while more though, so we get bug reports like this one. I normally never run MPI nowadays.

I'm looking into changing it to sth like `$JOHN/.JtR_kernel_build_lock` and using open(2) (and keeping an equivalent to @claudioandre-br's bug fix).

**Comment by magnumripper** [comment]
#3483 should have fixed this

**Comment by magnumripper** [comment]
So if I use `O_EXLOCK` I wont need to explicitly lock it afterwards, right? Should I avoid that? Following a man page is easy peasy, actually being portable is a whole different beast.

**Comment by solardiz** [comment]
`O_EXLOCK` is non-portable. Yes, should avoid it.

Now that you've closed this issue, please make sure there's some other issue open for fixing the rest of the sub-issues pointed out in the comments here. Most importantly, creating / opening a file under `/tmp` without O_EXCL is a vulnerability, which we should keep in our tree even temporarily - we should fix ASAP, even if by dropping code.
