### ISSUE TITLE
Fork's wrong assumption

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3502]
* Since **available** is different from **requested**.

```
$ ../run/john -form:SHA256crypt-opencl alltests.in -incremental -max-run=50 -fork=2
Loaded 7 password hashes with 5 different salts (sha256crypt-opencl, crypt(3) $5$ [SHA256 OpenCL])
Cost 1 (iteration count) is 5000 for all loaded hashes
Node numbers 1-2 of 2 (fork)
Device 1: Tahiti [AMD Radeon HD 7900 Series]
Device 0: Juniper [AMD Radeon HD 6700 Green Edition]
Error: To fully use the 8 devices requested, you must specify --fork=8
(see doc/README-OPENCL)
```

**Comment by solardiz** [comment]
Maybe it should be a warning rather than an error, and should in fact say "available" rather than "requested", when no devices were explicitly requested.

**Comment by claudioandre-br** [comment]
On a second thought, I would say there are 2 situations.

1st one: skip the message and run (even if I only have one GPU);
2nd one: bail with error;

```
$ ../run/john [...] -fork=2 # Ok
$ ../run/john [...] -fork=2 -dev=0,1,2 # ERROR
```

**Comment by magnumripper** [comment]
There's room for individual preference here... and there are many different cases:
1. OP was `--fork=2` and no `--dev` given. Current behavior seems to be to just pick them in device number order, and then bail with error. I think it should pick the two best devices if available and not even warn (or possibly just a notice). If there's only one device available, perhaps it should simply print a notice about GPU being "overbooked" (which might be on purpose). Or not even print that, since it will print the device number and model anyway so you'll see what happens.
2. I think some things that definitely should give an error is saying `--fork=2 -dev=1,2,3` or `--fork=3 -dev=1,2`. They are explicitly requesting things that doesn't match.
3. Another case is neither saying `--fork` or `--dev`. That should (and does) just pick best GPU and not warn.
4. Third case is saying `-dev=1,2,3` without saying `--fork`. That should error (except for mscash2-opencl).

Then we have the special labels like `--dev=gpu`. If you have 5 GPUs it could be used for "all of them" but since it's less explicit than saying `--dev=1,2,3,4,5` I think it's less of an indicator you really wanted all of them:

5. Let's say you use `--dev=gpu` on a machine with 5 GPUs, and no `--fork`. I think it should quietly pick the best GPU (like no. 3).
6. Let's say you use `--dev=gpu` on a machine with 5 GPUs, and `--fork=4`. Again since we didn't *explicitly* list too many devices, it's not an error but it should ideally use *the four best* ones if we can achieve that (just using `opencl_speed_index()` should be fine - perhaps we should query that when we build the device list, and then sort it accordingly instead of by device number).
7. Let's say you use `--dev=gpu` on a machine with 5 GPUs and `--fork=6`. This is same error as no. 2 `--fork=3 -dev=1,2` so should error.

Are there more cases?

**Comment by claudioandre-br** [comment]
> --fork=3 -dev=1,2. They are explicitly requesting things that doesn't match.

I can see a use case: suppose `--dev=1` is twice as fast as `--dev=2`. So I'd rather keep it as it is.

**Comment by claudioandre-br** [comment]
> I think it should quietly pick the best GPU.

We decided to defer OpenCL initialization in a remote past. To make it work as stated above, we will need to load OpenCL stuff earlier.

But there is another workaround; we can start to list GPUs by its "power", and stop listing it by its OpenCL number. So, a `--dev=gpu` will mean:
* the fastest;
* the second place;
* ...

Not 0,1,2,3, ...

**Comment by magnumripper** [comment]
> > I think it should quietly pick the best GPU.
> 
> We decided to defer OpenCL initialization in a remote past. To make it work as stated above, we will need to load OpenCL stuff earlier.
> 
> But there is another workaround; we can start to list GPUs by its "power", and stop listing it by its OpenCL number. So, a `--dev=gpu` will mean:
> 
> * the fastest;
> * the second place;
> * ...
> 
> Not 0,1,2,3, ...

If I understand you right now, that's what I meant: Using eg. `--dev=0` should still be first device on first platform, but `--dev=gpu` on super should currently be 6, 7, 2, 1, 0 while `--dev=all` should be 5, 6, 7, 2, 1, 0, 3, 4

**Comment by claudioandre-br** [comment]
> Do you mean you want two processes on device 1? Then you'd say -fork=3 -dev=1,1,2 and it will match.

Ok, it is a possibility and the code change will be minimal. But, JtR syntax will change in (fast hash) cases from `$ JtR [...] --fork=4 --dev=1` to `$ JtR [...] --fork=4 --dev=1,1,1,1`
***
If no one opposes, the one line validation will change from `devices requested < fork` to `devices requested != fork`.

**Comment by claudioandre-br** [comment]
> Using eg. --dev=0 should still be first device on first platform, but --dev=gpu on super should currently be 6, 7, 2, 1, 0 while --dev=all should be 5, 6, 7, 2, 1, 0, 3, 4

Exactly. And `dev=0` is still Juniper.

**Comment by magnumripper** [comment]
> > Do you mean you want two processes on device 1? Then you'd say -fork=3 -dev=1,1,2 and it will match.
> 
> Ok, it is a possibility and the code change will be minimal. But, JtR syntax will change in (fast hash) cases from `$ JtR [...] --fork=4 --dev=1` to `$ JtR [...] --fork=4 --dev=1,1,1,1`
> 
> If no one opposes, the one line validation will change from `devices requested < fork` to `devices requested != fork`.

That's OK, but it's a bit ambiguous. If that's what people are using now, let's keep it as-is. Sorting --dev=gpu et. al by speed would be awesome though.

**Comment by magnumripper** [comment]
> > Using eg. --dev=0 should still be first device on first platform, but --dev=gpu on super should currently be 6, 7, 2, 1, 0 while --dev=all should be 5, 6, 7, 2, 1, 0, 3, 4
> 
> In fact, I think is 6,2,7,1,0

Not when I looked. Perhaps clocks fluctuate? I've seen that before. Speed is simply `(clock * cores * width)`.
```
    Device #0 (0) name:     Juniper
    Device type:            GPU (LE)
    Speed index:            504000
    Device #1 (1) name:     Tahiti
    Device type:            GPU (LE)
    Speed index:            1026048
    Device #2 (2) name:     Tahiti
    Device type:            GPU (LE)
    Speed index:            2150400
    Device #3 (3) name:     Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
    Device type:            CPU (LE)
    Speed index:            332928
    Device #0 (4) name:     Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
    Device type:            CPU (LE)
    Speed index:            332800
    Device #1 (5) name:     Intel(R) Many Integrated Core Acceleration Card
    Device type:            Accelerator (LE)
    Speed index:            3972352
    Device #0 (6) name:     GeForce GTX TITAN X
    Device type:            GPU (LE)
    Speed index:            3305472
    Device #1 (7) name:     GeForce GTX TITAN
    Device type:            GPU (LE)
    Speed index:            2564352
```
I'm thinking we might use `width / 2` instead - it's weird that the MIC gets higher speed than the Titan X, that is so not true. Comparing GPUs to GPUs, the figure is pretty good for a rough indication.

**Comment by claudioandre-br** [comment]
We will use the `Speed index` and that is it. 
* Anyway, Tahiti seems better than GeForce GTX TITAN in all formats I used there. But, we are now talking about how compute the `Speed index` (another issue).

**Comment by solardiz** [comment]
> it's weird that the MIC gets higher speed than the Titan X

I guess that's because MIC's "core" count accounts for SMT threads, but GPUs' don't. Ideally, we'd arrive at a way to retrieve the physical SIMD unit counts directly, consistently excluding SMT from this calculation for all devices.
