### ISSUE TITLE
John rules do not work with Cyrillic

### ISSUE THREAD

**Issue by torerobo** [magnumripper/JohnTheRipper#3662]
Version: 1.8.0.13-jumbo-1-bleeding-43ed1a4f6 2018-11-23 19:32:37 +0100
Build: linux-gnu 64-bit x86_64 SSE4.1 AC OMP
GNU/Linux UTF-8

I created a dictionary of 3 words (2 Cyrillic + 1 Latin)
> пример
> пароль
> password
 
Edited john.conf, adding
[List.Rules: test]
**:
r
u
l
f
}
d**

Here is what I get
john2 -w=/word.txt --stdout --rules=test
пример
пароль
password
�ѵмиЀѿ�
�ѻоЀѰп�
drowssap
пример
пароль
PASSWORD
пример
пароль
password
пример�ѵмиЀѿ�
пароль�ѻоЀѰп�
passworddrowssap
примерпример
парольпароль
passwordpassword
�приме�
�парол�
dpasswor
21p 0:00:00:00 100,00% (2019-02-28 10:02) 150.0p/s dpasswor

![1](https://user-images.githubusercontent.com/35532898/53547632-9bd6c480-3b40-11e9-8611-c83e3db9529c.png)
Note that the option [**l** and **d** and **colon**] worked correctly (simple command)

Also, repeating simple commands gives the correct conclusion, for example
[List.Rules: test]
r r

Terminal output
The word turned twice and was not distorted.
пример
пароль
password

**Comment by frank-dittrich** [comment]
Try adding `--internal-codepage=koi8-r` to zthe command line options.

**Comment by frank-dittrich** [comment]
Explanation: The rules assume single-byte characters. The `--internal-codepage=koi8-r` converts the UTF-8 to KOI8-R before applying the rules, and converts back to UTF-8 before output.
(This works as long as you only have cyrillic characters and ASCII characters, but not a mix of cyrillic and western european non-ascii characters like ö, ä, ü or eastern european non-ascii characters like ł etc, because those would require different internal code page settings.

BTW: That question would have been more apropriate on the john-users mailing list.

**Comment by jfoug** [comment]
```
$ /d/JtR/bleed-64/run/john -w=in -stdout -rules=test --internal-codepage=koi8-r
ремирп
ьлорап
drowssap
ПРИМЕР
ПАРОЛЬ
PASSWORD
пример
пароль
password
примерремирп
паролььлорап
passworddrowssap
рприме
ьпарол
dpasswor
примерпример
парольпароль
passwordpassword
18p 0:00:00:00 100.00% (2019-02-28 03:46) 90.90p/s passwordpassword
```

**Comment by magnumripper** [comment]
Please read doc/ENCODINGS for more information.
