### ISSUE TITLE
The unicode_range.c pragma is not portable

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3691]
JtR CI will fail.

``` 
In file included from subsets.c:46:
./unicode_range.c:2:13: error: unknown pragma ignored
      [-Werror,-Wunknown-pragmas]
#pragma GCC push_options
            ^
./unicode_range.c:3:13: error: unknown pragma ignored
      [-Werror,-Wunknown-pragmas]
#pragma GCC optimize ("O0")
            ^
./unicode_range.c:2286:13: error: unknown pragma ignored
      [-Werror,-Wunknown-pragmas]
#pragma GCC pop_options
            ^
3 errors generated.
make[1]: *** [subsets.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [default] Error 2
```

**Comment by solardiz** [comment]
Does this happen with clang? Because it defines `__GNUC__` yet doesn't support these pragmas? I guess magnum should have used a PR for CI to run?

Anyway, I guess it's best to turn `unicode_range.c` into its own translation unit, and add `-O0` to it in a `Makefile` rule.

Alternatively, maybe the code in `unicode_range.c` can be changed e.g. by moving one instance of the loop into a function, then calling that function many times (perhaps pass to it a pointer to the current offset, or pointer to pointer, which it would advance). As long as we don't enable function inlining as a compiler optimization, this will probably not trigger excessive attempts at optimizing the branches nor register allocation, etc.

**Comment by claudioandre-br** [comment]
clang and Mac OS

https://travis-ci.com/magnumripper/JohnTheRipper/builds/105888519

**Comment by claudioandre-br** [comment]
http://clang.llvm.org/docs/LanguageExtensions.html#extensions-for-selectively-disabling-optimization

But it fails on well.
```
$ clang --version
clang version 3.4.2 (tags/RELEASE_34/dot2-final)
```
