### ISSUE TITLE
bitstream on ztex device is not updated automatically

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#3715]
I don't think that's a true bug or problem. JFYI I tried to run john builds with different bitstreams and it does not seem that john checks what bitstream is on device except for format name(?).

So it is easy to force reload of bitstream choosing other format with `--test`.

I can imagine the following scenarios with minor side effects:
- we update john in place and run new attack with the same format, bitstream is not updated, but frequency is set according to new john.conf,
- we update john in place and attach new device, so john uploads new bitstream to the new device and we have devices with different bitstreams (that's a guess; I did not try that).

Besides changes of frequency, the number of salts/hashes per devices may change between updates.

### System configuration ###
```
$ john --list=build-info
Version: 1.8.0.16-jumbo-1-bleeding-3c5f576 2019-03-29 13:39:54 +0100
```

**Comment by solardiz** [comment]
Known issue, at least to me. Maybe @Apingis should have updated descrypt-ztex's bitstream ID (the value 0x0101) this time (since so many things about it changed), but it's too late to do that now - not worth regenerating the bitstream and retesting. I agree this isn't "a true bug or problem" and so few people have ZTEX boards (or compatibles) that minor detail like this hardly matters. Also, we're probably done developing these formats - I expect no further updates to the bitstreams at this point.
