### ISSUE TITLE
Warning about too few candidates needs improvements

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#3718]
Minor cosmetic problem

I get the following warnings:
```
Warning: Only 1 candidates buffered for the current salt, minimum 12
needed for performance.
Warning: Only 2 candidates buffered for the current salt, minimum 12
needed for performance.
[...]
```
And each warning is split into 2 lines, it looks inconsistent with style of all other lines that are not split.

I see that it is intentional, in cracker.c:
```
fprintf(stderr, "Warning: Only %d candidates %s, "
        "minimum %d%cneeded for performance.\n",
        crk_key_index,
        single_running ? "buffered for the current salt" :
        mask_increments_len ? "buffered" : "left",
        crk_params->min_keys_per_crypt,
        single_running ? '\n' : ' ');
```

Then there is the following line. Splitting lines, it might be better to end sentences with full stop ".".
```
Almost done: Processing the remaining buffered candidate passwords, if any
```

**Comment by solardiz** [comment]
My preference would be not to split such lines. Let the terminal wrap them. These days, the terminal very often has more than 80 chars. Yes, we do have other examples where messages are split across two lines by JtR - maybe we need to remove that splitting as well.

Also, we shouldn't print the plural "candidates" when it's just 1. Should be "1 candidate".

And ideally we'd somehow indicate that these are pre-device-mask candidates when on-device mask is in use. It's confusing otherwise.

**Comment by magnumripper** [comment]
>  ideally we'd somehow indicate that these are pre-device-mask candidates when on-device mask is in use. It's confusing otherwise.

We can multiply the figures with the mask factor
```
../run/john all_tests.in -form:nt-opencl -w -mask
Warning: Only 35460000 candidates left, minimum 524288000 needed for performance.
```
or we can just have it say "base candidates" when GPU-side mask is in effect
```
Warning: Only 35460 base candidates left, minimum 524288 needed for performance.
```
