### ISSUE TITLE
A Windows binary in the tree?

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3844]
Is this file useful?
* https://github.com/magnumripper/JohnTheRipper/blob/master/src/john.com

Should it be used?

**Comment by solardiz** [comment]
This isn't a Windows binary - it is a DOS binary specific to DJGPP builds. It is still needed for our DOS support, where it provides symlink emulation. The binary is included because rebuilding it requires proprietary TASM. All of this comes from core. I'm thinking of dropping DOS support in two releases from now (that is, not in 1.9.0-jumbo-1 yet, but in the next major release after that), at which time this binary will also be gone.
