### ISSUE TITLE
apfs2john update

### ISSUE THREAD

**Issue by Banaanhangwagen** [magnumripper/JohnTheRipper#3847]
(new issue as asked here: https://github.com/magnumripper/JohnTheRipper/pull/3390#issuecomment-485052469)

`apfs-fuse` had some problems with blocksize 4096, but this is fixed now thanks to the great work of @sgan81
More info can be found here: https://github.com/sgan81/apfs-fuse/issues/74

Can `apfs2john` be updated also, in order to make it compatible with latest macOS images?

**Comment by solardiz** [comment]
I'm out of context here. Is this possibly a trivial enough yet important enough fix that we should get it into our upcoming release? If so, I'd appreciate a PR from someone familiar with this, or from someone who can figure it out soon enough. Thanks!

**Comment by sgan81** [comment]
The problem is that a physical block size of 4096 causes the partition table layout to be different. So the blocksize was only a problem when mounting disk images or whole drives. Otherwise, everything worked fine.
In the meantime, I have updated apfs-fuse so that the blocksize is detected automatically based on the partition table layout. But as I said, it was otherwise perfectly fine. I don't know what you need, but if you process partition tables in images or drives to find an APFS partition, it would probably be useful to add this fix.

**Comment by sgan81** [comment]
To be even more precise, normally an EFI partition table refers to 512 byte sectors. Now with Apple, with 4096 byte sectors, they also refer to 4096 byte sectors in the partition table, but this is not marked anywhere. The only hint is that the EFI partition table begins at offset 4096 instead of 512.

**Comment by Banaanhangwagen** [comment]
@kholia did a fork of `apfs-fuse` and changed the code of the tool `apfs-dump-quick` in order to extract the hash 

the most recent images of macOS (during my testing it started with Mojave) weren't parsed correctly any more because - as @sgan81 mentioned - Apple changed the partition table to physical block size of 4096

the `apfs-fuse` got updated, so kholia's `apfs-dump-quick` needs to get the same update

**Comment by solardiz** [comment]
Thank you for explaining this, @sgan81 and @Banaanhangwagen. Would one of you possibly send us a pull request with the corresponding update? We'd appreciate that. Thank you!

It appears that @kholia isn't currently available (judging by his response to this extent and his lack of activity lately on several other issues assigned to him).

**Comment by Banaanhangwagen** [comment]
I forked the project `apfs-fuse` and fixed the hash extraction.
https://github.com/Banaanhangwagen/apfs2hashcat

Happy cracking!

**Comment by magnumripper** [comment]
@Banaanhangwagen does that mean we don't need to change anything to JtR, or do we still need to? Also, did you send apfs-fuse upstream a PR with your fixes?

**Comment by Banaanhangwagen** [comment]
> does that mean we don't need to change anything to JtR, or do we still need to? 

This fork will do the trick to extract the hash. JtR does not need to be changed.

>Also, did you send apfs-fuse upstream a PR with your fixes?

No. I don't want to make @sgan81's project dirty. ;)
