### ISSUE TITLE
Null character(s) : !<symlink> ■x 8 6 - 6 4 . h

### ISSUE THREAD

**Issue by MALA19** [magnumripper/JohnTheRipper#3859]
When i´m building John, this error appears

`In file included from dashlane_fmt_plug.c:13:0:
arch.h:1:14: warning: null character(s) ignored
 !<symlink> ■x 8 6 - 6 4 . h
              ^
arch.h:1:16: warning: null character(s) ignored
 !<symlink> ■x 8 6 - 6 4 . h
                ^
arch.h:1:18: warning: null character(s) ignored
 !<symlink> ■x 8 6 - 6 4 . h
                  ^
arch.h:1:20: warning: null character(s) ignored
 !<symlink> ■x 8 6 - 6 4 . h
                    ^
arch.h:1:22: warning: null character(s) ignored
 !<symlink> ■x 8 6 - 6 4 . h
                      ^
arch.h:1:24: warning: null character(s) ignored
 !<symlink> ■x 8 6 - 6 4 . h
                        ^
arch.h:1:26: warning: null character(s) ignored
 !<symlink> ■x 8 6 - 6 4 . h
                          ^
arch.h:1:28: warning: null character(s) ignored
 !<symlink> ■x 8 6 - 6 4 . h`

is the same with other fmt plugs

**Comment by claudioandre-br** [comment]
I never saw this. Are you using Visual Studio? Editing source code using some fancy editor? ...?

You need to give us more information about the environment, what you did to get the source code, commands you are using, what version of JtR, etc?

Try to show us how to reproduce your problem.

**Comment by MALA19** [comment]
> I never saw this. Are you using Visual Studio? Editing source code using some fancy editor? ...?
> 
> You need to give us more information about the environment, what you did to get the source code, commands you are using, what version of JtR, etc?
> 
> Try to show us how to reproduce your problem.

I´m using  The "bleeding-jumbo, and I built it in the CygWin terminal with this command:

./configure && make -s clean && make -sj4

**Comment by claudioandre-br** [comment]
[Here](https://ci.appveyor.com/project/claudioandre-br/johntheripper/build/job/dj6qnvhthcoe48rv) I'm cloning and building using a CygWin shell (Windows Server 2012 and Windows Server 2016). So, the possible explanation is that one tool you are using is converting files to UTF-16.
- JtR + CygWin + git **work fine**.

Therefore, although this issue is worded as a bug report, not as a question, I'm afraid you're mistaken. 

- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message Subject when you post).

**Comment by magnumripper** [comment]
I too think this is somehow invalid. I can’t quite come up with an explanation though

**Comment by solardiz** [comment]
Could this be some Cygwin install time setting? Could this be related to underlying filesystem type? I recall Cygwin previously asked about conversion to DOS linefeeds. I wonder if it possibly has anything similar for UTF-16. But even then, these are Cygwin's own symlinks, so it'd suggest an inconsistent Cygwin install.

**Comment by solardiz** [comment]
Little point in keeping this non-reproducible issue open without further input from @MALA19, so I'm closing it.
