### ISSUE TITLE
Jim's "portable high-resolution timer" sometimes get low resolution

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3949]
This timer is currently used only in OMP/MKPC auto-tuning but since it's portable we could switch to it for OpenCL auto-tuning, benchmarks and other things as well.

Linux gets a `sm_hrPrecision` of 1 us, that's fine. Under macOS though, I get a resolution of about 200 us. Looking at `sm_cPrecision` we seem to detect an actual 1 us resolution from `clock()` so I'm not sure what  is happening.
MinGW claims 99 ns resolution. 64-bit on a CI see about 399 ns while 32-bit see 599 ns. They both might be affected by heavy load of host and are possibly also VMs.

Not sure whether it's just the trimming within `sTimer_Init()` that need to be enhanced, or some bug.

**Comment by magnumripper** [comment]
Simple fix.
```diff
-#define HRSETCURRENT(X)       { struct timezone tz; gettimeofday (&(X), &tz); }
+#define HRSETCURRENT(X)       { gettimeofday (&(X), NULL); }
```
The unneeded/irrelevant request of timezone information apparently gave a latency of 160-200 us.

**Comment by claudioandre-br** [comment]
This is Windows 2016
```
Version: 1.9.0-jumbo-1-bleeding-e65c2c4c4 2019-05-15 10:04:52 -0300
[...]
clock(3) CLOCKS_PER_SEC: 1000
times(2) sysconf(_SC_CLK_TCK) is 1000
Using times(2) for timers, resolution 1 ms
HR timer claimed resolution 99 ns, actual seen 99 ns
```

**Comment by solardiz** [comment]
`gettimeofday` is generally a wrong function to use for timers because it's affected by system time adjustments, such as those made by an NTP client service (or by the system kernel as previously told to by the NTP client service via `adjtime`), and indeed by manual system time changes.

Where available, we should possibly use:

```c
static uint64_t time_us(void)
{
	struct timespec t;
#ifdef CLOCK_MONOTONIC_RAW
	if (clock_gettime(CLOCK_MONOTONIC_RAW, &t))
		return 0;
#else
	if (clock_gettime(CLOCK_MONOTONIC, &t))
		return 0;
#endif
	return 1 + (uint64_t)t.tv_sec * 1000000 + t.tv_nsec / 1000;
}
```

(copy-paste from yescrypt/userom.c) or perhaps its equivalent with ns precision (adjusting the `return` line in the snippet above, and the function name). On some systems (at least with older glibc) this will require linking with `-lrt`, unfortunately.

Failing that, `times` is the next best thing not affected by system time adjustments, but instead we might in fact prefer `gettimeofday` for its higher resolution anyway.

Overall, I think Jim's code is too large for what it does. Perhaps we can use fewer (semi-)portable alternatives.

**Comment by magnumripper** [comment]
I don't think it's large, but I dislike the fact it's using `double` instead of `uint64_t`.
