### ISSUE TITLE
Fedora gcc 9 is complaining about JtR code

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3955]
Fedora release 30 (Thirty)
gcc (GCC) 9.0.1 20190312 (Red Hat 9.0.1-0.10)

```
Configure finished.  Now "make -s clean && make -sj4" to compile.
ar: creating aes.a
ar: creating ed25519-donna.a
ar: creating secp256k1.a
dynamic_fmt.c: In function 'prepare':
dynamic_fmt.c:1088:36: error: '$$F' directive output may be truncated writing 3 bytes into a region of size between 1 and 1024 [-Werror=format-truncation=]
 1088 |      snprintf(ct2, sizeof(ct2), "%s$$F%d%s", cpBuilding, i, split_fields[i]);
      |                                    ^~~
dynamic_fmt.c:1088:33: note: directive argument in the range [0, 9]
 1088 |      snprintf(ct2, sizeof(ct2), "%s$$F%d%s", cpBuilding, i, split_fields[i]);
      |                                 ^~~~~~~~~~~
dynamic_fmt.c:1088:6: note: 'snprintf' output 5 or more bytes (assuming 1028) into a destination of size 1024
 1088 |      snprintf(ct2, sizeof(ct2), "%s$$F%d%s", cpBuilding, i, split_fields[i]);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:1778: dynamic_fmt.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:190: default] Error 2
Exited with code 2
```

Interesting, It works on gcc from Ubuntu. No warnings when using the compiler below.
gcc (Ubuntu 20190302-1ubuntu1) 9.0.1 20190302 (experimental) [trunk revision 269338]

**Comment by claudioandre-br** [comment]
This should be a discussion about what warnings mute or fix. And if it is feasible to use `-wError`

**Comment by solardiz** [comment]
Why does Fedora's gcc call "$$F" a directive here? Where is that documented? I tried googling - no luck.

Anyway, maybe splitting the string in two like `"%s$" "$F%d%s"` will avoid the first two warnings.

**Comment by ghost** [comment]
gcc 10 on Fedora is not complaining about this. But, the build is not "clean". 

Anyway, I'm more concerned with compiler flags and/or silencing warnings. Eventually, if we should avoid `-wError`.

All recent versions of gcc and clang are complaining a lot.
****
@magnumripper commented about a review of the compilation flags recently.
****

As an example, I can use `--enable-werror` in all my "stable builds". But I can't for everything else.
![image](https://user-images.githubusercontent.com/1702923/83976000-7e5ce280-a8cd-11ea-9cdb-40c4f43109f7.png)

**Comment by solardiz** [comment]
I couldn't reproduce the specific warnings/errors (reported on Fedora 30 here) using my builds of gcc 8.4.0, 9.1.0, nor any other release. I suspect this was a temporary gcc bug in some snapshot of 9.0.1. With their current version numbering scheme, gcc versions x.0.y are considered prereleases and are not expected to be as stable as gcc releases (x.1.y and higher).

I'm unsure if we should workaround a temporary gcc bug like this, although I wouldn't mind.

> Anyway, I'm more concerned with compiler flags and/or silencing warnings. Eventually, if we should avoid `-wError`.

I think we should proceed like we've been doing so far. Don't silence warnings, patch them in code where we reasonably can, don't enable `-Werror` for users by default, have a way to enable it when explicitly requested, sometimes enable it for our own CI and/or other test builds when we feel that is beneficial (e.g., on specific gcc versions where we currently have no warnings, so that we don't introduce such regressions).

**Comment by solardiz** [comment]
Apparently, Fedora 30 updates contain gcc 9.3.1 now, so the 9.0.1 problem would only affect those who installed Fedora 30 and don't update it. Or maybe even only those who updated Fedora 30 to a particular past revision yet don't update it anymore, because their 9.0.1 has been changing (Claudio's report here is for -0.10, but there were also -0.9, -0.8, etc.)

This should explain why we didn't have this issue reported to us by any user.

**Comment by ghost** [comment]
BTW: I have to audit everything, but I would say we are almost done:

```
Configure finished.  Now "make -s clean && make -sj4" to compile.
bcrypt_pbkdf_plug.c:81:40: warning: expression does not compute the number of elements in this array; element type is 'uint32_t' (aka 'unsigned int'), not 'uint64_t' (aka 'unsigned long') [-Wsizeof-array-div]
                blf_enc(&state, cdata, sizeof(cdata) / sizeof(uint64_t));
                                              ~~~~~  ^
bcrypt_pbkdf_plug.c:62:11: note: array 'cdata' declared here
        uint32_t cdata[BCRYPT_WORDS];
                 ^
bcrypt_pbkdf_plug.c:81:40: note: place parentheses around the 'sizeof(uint64_t)' expression to silence this warning
                blf_enc(&state, cdata, sizeof(cdata) / sizeof(uint64_t));

gpg2john.c:1611:4: warning: misleading indentation; statement is not part of the previous 'if' [-Wmisleading-indentation]
                        if (gpg_dbg) fprintf(stderr, "(%d bytes) partial start\n", len);
                        ^
gpg2john.c:1609:3: note: previous statement is here
                if (partial == YES)
```

**Comment by solardiz** [comment]
@claudioandre-br Somehow I'm not getting these warnings on any gcc builds I have. Where are you getting them? When building for what arch? Would you please make a PR fixing them? Thank you!

**Comment by ghost** [comment]
I still need to analyse all CI stuff. The warnings can be seeing at:
* https://travis-ci.org/github/claudioandre-br/JohnTheRipper/jobs/696598789

**Comment by solardiz** [comment]
So these are on:
```
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
```

**Comment by ghost** [comment]
Sorry, no. It is `clang version 10.0.1`.
Line: 232 => OS info.
Line: 330 => Compiler info.
