### ISSUE TITLE
Mute "Warning: Only n candidates buffered for the current salt" under certain circumstances

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3986]
Quoting @solardiz from off-list discussion:
> Maybe we need to somehow mute those warnings when running against fast hashes with no or few salts.  Maybe check the p/s rate achieved so far, and if the insufficient buffering appears to correspond to less than 1 second, then mute the message.  In other words, mute if p/s is numerically higher than the difference between min_keys_per_crypt and actual buffer fill.  In this case, p/s > 24-18.  I'm not sure what the p/s would be calculated to be so early in the run (I think at end of single crack pass), but perhaps not that tiny a number.

**Comment by solardiz** [comment]
I realized that for "single crack" mode high p/s doesn't imply we finish or advance to next pass of batch mode so soon the warning doesn't matter (and thus doesn't need to be printed). Since with that mode the buffers are per-salt, high salt count may also slow things down. So perhaps use p/s as I suggested for muting the warnings in all other cracking modes, but when we're in "single crack" use p/s divided by  salt count in that comparison I suggested. (In the original context for the above quote, the hash was unsalted, so this made no difference.)

Be careful not to divide by zero in case everything just got cracked.
