### ISSUE TITLE
Support building without HAVE_BIO_NEW (BIO_* functions in crypto library)

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#616]
See also #605 and 705e9c1

Affected files:
- [x] luks2john.c
- [x] pfx2john.c
- [x] pfx_fmt.c
- [x] ssh2john.c
- [x] ssh_fmt.c
- [x] ssh_ng_fmt_plug.c
- [x] Makefile.in

**Comment by jfoug** [comment]
@magnumripper can you please validate after b3293b0 that this issue is corrected?

Should we also add similar logic for the other HAVE_SSL_STUFF macros ?

```
checking for EVP_aes_256_xts... (cached) yes
checking for SHA256... (cached) yes
checking for WHIRLPOOL... (cached) yes
checking for RIPEMD160... (cached) yes
checking for AES_encrypt... (cached) yes
checking for EVP_sha512... (cached) yes
checking for BIO_new... (cached) yes
```

I think WHIRLPOOL and RIPEMD160 are already handled for sure (with fall back code to sph_* functions).  I think the others are not checked for in code.

**Comment by magnumripper** [comment]
We should add it if some systems need it.

Maybe we should try to drop OpenSSL completely. We do have our own code for most everything low-level. But some formats might be tricky because they use higher level interfaces.
