### ISSUE TITLE
pdf2john.py does not extract pdf document with locked printing

### ISSUE THREAD

**Issue by martiGIT** [magnumripper/JohnTheRipper#761]
While extracting password from pdf file with locked printing (only), hash is extracted, but cracking results with empty password (I assume that password hash is taken only form file lock, which in fact is empty). No option to extract printing password.

**Comment by ShaneQful** [comment]
So after having a little look at the issue, the older pdf2john.c could do this but only for really old versions of the pdf spec. In order to do this properly for all versions the algorithms for generating the owner password have to be implemented. Unfortunately we can't just take these from other open source projects as most don't bother to implent them as it's kinda pointless DRM that only works if you open the pdf in an adobe product.

Essentially the fix is to implement the algorithms described here : http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf

And to add a flag in the to say which password you want. 

Going to remove myself as assignee as work is a bit hectic at the moment and I don't have the time to work on this, apologies.

**Comment by kholia** [comment]
@ShaneQful thanks for all the research on this topic!

I agree that it seems to be pretty pointless to implement this, the reporter can simply use "Sumatra PDF reader" to bypass owner password restrictions. Should we just close this ticket?

**Comment by ShaneQful** [comment]
Yeah I think we can close it. I don't think any other pdf viewer other than adobe's even bothers to check the field. If one of the open source pdf viewers start to do this check we can always take their code once it's implemented.
