### ISSUE TITLE
dmg2john Python and C versions produce different hashes

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#869]
https://github.com/magnumripper/JohnTheRipper/issues/520#issuecomment-64427153

jfoug:

> I was able to dump a hash from here: https://github.com/kholia/VileFault/blob/master/tests/one.sparseimage.secret.sparseimage with python. The hash was very different than the one given by dmg2john exe file, but it still cracked.

magnumripper:

> This is odd. I tried the same, with same results. Stripping out just the hash field, they differ in size with three bytes. The funny thing is the python version consists of 68% zeroes whereas the C version only has one short train of zeroes near the beginning. Maybe this means we can make the output of both a lot shorter?

We should try to establish why they produce different output (ideally they would be the exact same) and whether we can actually shorten the output of both.

**Comment by kholia** [comment]
We have deprecated the usage of `dmg2john.py` now. So I think that this very old issue this can be closed now.

**Comment by solardiz** [comment]
> We have deprecated the usage of dmg2john.py now.

OK, although that's unfortunate: `dmg2john.py` is (was?) the primary tool to use when intending to crack the password on system(s) other than the original OS X system the dmg file or sparse bundle is on. And that's in fact what I'd recommend, if we had that script more up-to-date and maintained.

Anyway, this increases the importance of having up-to-date binary builds of jumbo for OS X, so that the compiled `dmg2john` could be used.

**Comment by magnumripper** [comment]
I think @kholia meant "we" in a royal sense 😆 The python tool is still in the repo. The other version supports more versions/variants though.
