### ISSUE TITLE
lastpass2john.py no longer works

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#890]
The format of the lastpass has changed, I believe, and this tool no longer works.  I think the actual hash function is the same, by reading the LastPass site, the algorithm sounds the same.  BUT the tool no longer works.

**Comment by kholia** [comment]
I am in favor of dropping this format, and declaring LastPass to be "crap" ;)

* http://www.tobtu.com/lastpass.php

* https://github.com/HyShai/lastpass-pythonista (ideas for fixing this ticket)

**Comment by magnumripper** [comment]
The fact it's crap make it all the more suitable for JtR though.

**Comment by smarteam** [comment]
how about trying to bring it back?

Encryption can be tested here (JS): https://lastpass.com/js/enc.php

testlastpasstest@mailinator.com with default 5000 rounds and "L@$tP@$$w0rd" successfully decrypts third line from .sch file as email address

![image](https://cloud.githubusercontent.com/assets/1858405/9170030/03c03050-3f68-11e5-8320-e3efca2b3688.png)

**Comment by kholia** [comment]
https://systemoverlord.com/blog/2015/09/16/what-the-lastpass-cli-tells-us-about-lastpass-design/

https://github.com/lastpass/lastpass-cli

These might help us fix this format.

**Comment by Fist0urs** [comment]
Ok, I've taken a quick look to this shit and actually the problem seems to be, for me, to find the iteration number.

By default number of iterations for pbkdf2-sha256 is 5000, but users can lower this (I don't know the condition, I've read something related to premium account or thing like that(?)), and if user lowers it to 1, then raw-sha256 is used.

Concerning AES 256, there is two possibilities:
* the blob begins with '!' => the next 16 bytes are the salt used for CBC mode and last 32 bytes are ciphertext
* otherwise ECB mode is used

And I haven't seen anyway to get iteration number just looking at the blob :( (well, I don't really know this software. I just know that it is quite used so we should take a look...)

**Comment by kholia** [comment]
Both LastPass v3.x and LastPass CLI are now supported properly with the recent PRs.
